// @author qleelulu@gmail.com

// 新浪微博表情转化
var TSINA_FACE_URL_PRE = 'http://timg.sjs.sinajs.cn/t35/style/images/common/face/ext/normal/';
var TSINA_FACE_TPL = '[{{name}}]';
var TSINA_FACES = {
"呵呵": "eb/smile.gif",
"嘻嘻": "c2/tooth.gif",
"哈哈": "6a/laugh.gif",
"爱你": "7e/love.gif",
"晕": "a4/dizzy.gif",
"泪": "d8/sad.gif",
"馋嘴": "b8/cz_thumb.gif",
"抓狂": "4d/crazy.gif",
"哼": "19/hate.gif",
"抱抱": "7c/bb_thumb.gif",
"可爱": "9c/tz_thumb.gif",
"怒": "57/angry.gif",
"汗": "13/sweat.gif",
"困": "8b/sleepy.gif",
"害羞": "05/shame_thumb.gif",
"睡觉": "7d/sleep_thumb.gif",
"钱": "90/money_thumb.gif",
"偷笑": "7e/hei_thumb.gif",
"酷": "40/cool_thumb.gif",
"衰": "af/cry.gif",
"吃惊": "f4/cj_thumb.gif",
"闭嘴": "29/bz_thumb.gif",
"鄙视": "71/bs2_thumb.gif",
"挖鼻屎": "b6/kbs_thumb.gif",
"花心": "64/hs_thumb.gif",
"鼓掌": "1b/gz_thumb.gif",
"失望": "0c/sw_thumb.gif",
"思考": "e9/sk_thumb.gif",
"生病": "b6/sb_thumb.gif",
"亲亲": "8f/qq_thumb.gif",
"怒骂": "89/nm_thumb.gif",
"太开心": "58/mb_thumb.gif",
"懒得理你": "17/ldln_thumb.gif",
"右哼哼": "98/yhh_thumb.gif",
"左哼哼": "6d/zhh_thumb.gif",
"嘘": "a6/x_thumb.gif",
"委屈": "73/wq_thumb.gif",
"吐": "9e/t_thumb.gif",
"可怜": "af/kl_thumb.gif",
"打哈气": "f3/k_thumb.gif",
"顶": "91/d_thumb.gif",
"疑问": "5c/yw_thumb.gif",
"做鬼脸": "88/zgl_thumb.gif",
"握手": "0c/ws_thumb.gif",
"耶": "d9/ye_thumb.gif",
"good": "d8/good_thumb.gif",
"弱": "d8/sad_thumb.gif",
"不要": "c7/no_thumb.gif",
"ok": "d6/ok_thumb.gif",
"赞": "d0/z2_thumb.gif",
"来": "40/come_thumb.gif",
"蛋糕": "6a/cake.gif",
"心": "6d/heart.gif",
"伤心": "ea/unheart.gif",
"钟": "d3/clock_thumb.gif",
"猪头": "58/pig.gif",
"话筒": "1b/m_thumb.gif",
"月亮": "b9/moon.gif",
"太阳": "e5/sun.gif",
"下雨": "50/rain.gif",
"咖啡": "64/cafe_thumb.gif",
"干杯": "bd/cheer.gif",
"绿丝带": "b8/green.gif",
"蜡烛": "cc/candle.gif",
"微风": "a5/wind_thumb.gif",
"月亮": "b9/moon.gif",
"月饼": "96/mooncake3_thumb.gif",
"满月": "5d/moon1_thumb.gif",
"酒壶": "64/wine_thumb.gif",
"团": "11/tuan_thumb.gif",
"圆": "53/yuan_thumb.gif",
"左抱抱": "54/left_thumb.gif",
"右抱抱": "0d/right_thumb.gif",
"乐乐": "66/guanbuzhao_thumb.gif",
"团圆月饼": "e6/tuanyuan_thumb.gif",
"快快": "49/lbq1_thumb.gif",
"织": "41/zz2_thumb.gif",
"围观": "f2/wg_thumb.gif",
"威武": "70/vw_thumb.gif",
"爱心传递": "c9/axcd_thumb.gif",
"奥特曼": "bc/otm_thumb.gif",
// 亚运
"国旗": "dc/flag_thumb.gif",
"金牌": "f4/jinpai_thumb.gif",
"银牌": "1e/yinpai_thumb.gif",
"铜牌": "26/tongpai_thumb.gif",
"围脖": "3f/weijin_thumb.gif",
"温暖帽子": "f1/wennuanmaozi_thumb.gif",
"手套": "72/shoutao_thumb.gif",
"落叶": "79/yellowMood_thumb.gif",
"照相机": "33/camera_thumb.gif",
"礼物": "c4/liwu_thumb.gif",
"v5": "c5/v5_org.gif",
"书呆子": "61/sdz_org.gif",
"男孩儿": "4e/kissboy_org.gif",
"女孩儿": "1b/kissgirl_org.gif",
"风扇": "92/fan.gif",
"冰棍": "3a/ice.gif",
"西瓜": "6b/watermelon.gif",
"给力": "c9/geili_thumb.gif",
"神马": "60/horse2_thumb.gif",
"浮云": "bc/fuyun_thumb.gif",
"兔子": "81/rabbit_thumb.gif",

"猥琐": "e1/weisuo_thumb.gif",
"挑眉": "c9/tiaomei_thumb.gif", 
"挑逗": "3c/tiaodou_thumb.gif",
"亲耳朵": "1c/qinerduo_thumb.gif",
"媚眼": "32/meiyan_thumb.gif",
"冒个泡": "32/maogepao_thumb.gif",
"囧耳朵": "f0/jiongerduo_thumb.gif",
"鬼脸": "14/guilian_thumb.gif",
"放电": "fd/fangdian_thumb.gif",
"悲剧": "ea/beiju_thumb.gif"
};

// python create_emotions_data.py
// 再将结果翻译成繁体 http://translate.google.com/
// 繁体会有问题，需要查看此微博调试 http://weibo.com/1828485392/xyxxpm7AW
var TSINA_API_EMOTIONS = {
"织": "41/zz2_org.gif", "神马": "60/horse2_org.gif", "浮云": "bc/fuyun_org.gif", "给力": "c9/geili_org.gif", "围观": "f2/wg_org.gif", "威武": "70/vw_org.gif", "熊猫": "6e/panda_org.gif", "兔子": "81/rabbit_org.gif", "奥特曼": "bc/otm_org.gif", "囧": "15/j_org.gif", "互粉": "89/hufen_org.gif", "礼物": "c4/liwu_org.gif", "呵呵": "ac/smilea_org.gif", "嘻嘻": "0b/tootha_org.gif", "哈哈": "6a/laugh.gif", "可爱": "14/tza_org.gif", "可怜": "af/kl_org.gif", "挖鼻屎": "a0/kbsa_org.gif", "吃惊": "f4/cj_org.gif", "害羞": "6e/shamea_org.gif", "挤眼": "c3/zy_org.gif", "闭嘴": "29/bz_org.gif", "鄙视": "71/bs2_org.gif", "爱你": "6d/lovea_org.gif", "泪": "9d/sada_org.gif", "偷笑": "19/heia_org.gif", "亲亲": "8f/qq_org.gif", "生病": "b6/sb_org.gif", "太开心": "58/mb_org.gif", "懒得理你": "17/ldln_org.gif", "右哼哼": "98/yhh_org.gif", "左哼哼": "6d/zhh_org.gif", "嘘": "a6/x_org.gif", "衰": "af/cry.gif", "委屈": "73/wq_org.gif", "吐": "9e/t_org.gif", "打哈气": "f3/k_org.gif", "抱抱": "27/bba_org.gif", "怒": "7c/angrya_org.gif", "疑问": "5c/yw_org.gif", "馋嘴": "a5/cza_org.gif", "拜拜": "70/88_org.gif", "思考": "e9/sk_org.gif", "汗": "24/sweata_org.gif", "困": "7f/sleepya_org.gif", "睡觉": "6b/sleepa_org.gif", "钱": "90/money_org.gif", "失望": "0c/sw_org.gif", "酷": "40/cool_org.gif", "花心": "8c/hsa_org.gif", "哼": "49/hatea_org.gif", "鼓掌": "36/gza_org.gif", "晕": "d9/dizzya_org.gif", "悲伤": "1a/bs_org.gif", "抓狂": "62/crazya_org.gif", "黑线": "91/h_org.gif", "阴险": "6d/yx_org.gif", "怒骂": "89/nm_org.gif", "心": "40/hearta_org.gif", "伤心": "ea/unheart.gif", "猪头": "58/pig.gif", "ok": "d6/ok_org.gif", "耶": "d9/ye_org.gif", "good": "d8/good_org.gif", "不要": "c7/no_org.gif", "赞": "d0/z2_org.gif", "来": "40/come_org.gif", "弱": "d8/sad_org.gif", "蜡烛": "91/lazu_org.gif", "钟": "d3/clock_org.gif", "蛋糕": "6a/cake.gif", "话筒": "1b/m_org.gif", "bed蹬腿": "d5/brddengtui_org.gif", "bed飘忽": "9c/brdpiaohu_org.gif", "j撒娇": "d9/xyjsajiao_org.gif", "j挂了": "b4/xyjguale_org.gif", "萌萌扭屁股": "4b/mmniupigu_org.gif", "萌萌偷乐": "95/mmwuzuile_org.gif", "ala上火": "1b/altshanghuo_org.gif", "ala啊哈哈哈": "6a/altahahaha_org.gif", "好爱哦": "74/lxhainio_org.gif", "羞嗒嗒": "df/lxhxiudada_org.gif", "转发": "02/lxhzhuanfa_org.gif", "路过这儿": "ac/lxhluguo_org.gif", "挤眼": "c3/zy_org.gif", "亲亲": "8f/qq_org.gif", "怒骂": "89/nm_org.gif", "太开心": "58/mb_org.gif", "懒得理你": "17/ldln_org.gif", "打哈气": "f3/k_org.gif", "生病": "b6/sb_org.gif", "书呆子": "61/sdz_org.gif", "失望": "0c/sw_org.gif", "可怜": "af/kl_org.gif", "黑线": "91/h_org.gif", "吐": "9e/t_org.gif", "委屈": "73/wq_org.gif", "思考": "e9/sk_org.gif", "哈哈": "6a/laugh.gif", "嘘": "a6/x_org.gif", "右哼哼": "98/yhh_org.gif", "左哼哼": "6d/zhh_org.gif", "疑问": "5c/yw_org.gif", "阴险": "6d/yx_org.gif", "顶": "91/d_org.gif", "钱": "90/money_org.gif", "悲伤": "1a/bs_org.gif", "鄙视": "71/bs2_org.gif", "拜拜": "70/88_org.gif", "吃惊": "f4/cj_org.gif", "闭嘴": "29/bz_org.gif", "衰": "af/cry.gif", "愤怒": "bd/fn_org.gif", "感冒": "a0/gm_org.gif", "酷": "40/cool_org.gif", "来": "40/come_org.gif", "good": "d8/good_org.gif", "haha": "13/ha_org.gif", "不要": "c7/no_org.gif", "ok": "d6/ok_org.gif", "拳头": "cc/o_org.gif", "弱": "d8/sad_org.gif", "握手": "0c/ws_org.gif", "赞": "d0/z2_org.gif", "耶": "d9/ye_org.gif", "最差": "3e/bad_org.gif", "可爱": "14/tza_org.gif", "嘻嘻": "0b/tootha_org.gif", "汗": "24/sweata_org.gif", "呵呵": "ac/smilea_org.gif", "困": "7f/sleepya_org.gif", "睡觉": "6b/sleepa_org.gif", "害羞": "6e/shamea_org.gif", "泪": "9d/sada_org.gif", "爱你": "6d/lovea_org.gif", "挖鼻屎": "a0/kbsa_org.gif", "花心": "8c/hsa_org.gif", "偷笑": "19/heia_org.gif", "心": "40/hearta_org.gif", "哼": "49/hatea_org.gif", "鼓掌": "36/gza_org.gif", "晕": "d9/dizzya_org.gif", "馋嘴": "a5/cza_org.gif", "抓狂": "62/crazya_org.gif", "抱抱": "27/bba_org.gif", "怒": "7c/angrya_org.gif", "右抱抱": "0d/right_org.gif", "左抱抱": "54/left_org.gif", "吃汤圆": "52/lxhchitangyuan_org.gif", "耍花灯": "be/lxhshuahuadeng_org.gif", "元宵快乐": "83/lxhyuanxiaohappy_org.gif", "玫瑰": "f6/lxhrose_org.gif", "好爱哦": "74/lxhainio_org.gif", "羞嗒嗒": "df/lxhxiudada_org.gif", "中箭": "81/lxhzhongjian_org.gif", "丘比特": "35/lxhqiubite_org.gif", "放电抛媚": "d0/lxhfangdianpaomei_org.gif", "被电": "ed/lxhbeidian_org.gif", "转发": "02/lxhzhuanfa_org.gif", "路过这儿": "ac/lxhluguo_org.gif", "赞啊": "00/lxhzan_org.gif", "推荐": "e9/lxhtuijian_org.gif", "萌翻": "99/lxhmengfan_org.gif", "挤火车": "09/lxhjihuoche_org.gif", "赶火车": "a2/lxhganhuoche_org.gif", "求关注": "ac/lxhqiuguanzhu_org.gif", "好喜欢": "d6/lxhlike_org.gif", "同意": "14/lxhtongyi_org.gif", "许愿": "87/lxhxuyuan_org.gif", "瞧瞧": "8b/lxhqiaoqiao_org.gif", "牛": "24/lxhniu_org.gif", "杰克逊": "e5/lxhjiekexun_org.gif", "膜拜了": "52/lxhmobai_org.gif", "互相膜拜": "3c/lxhhuxiangmobai_org.gif", "拍砖": "3b/lxhpaizhuan_org.gif", "互相拍砖": "5b/lxhhuxiangpaizhuan_org.gif", "采访": "8b/lxhcaifang_org.gif", "发表言论": "f1/lxhfabiaoyanlun_org.gif", "霹雳": "41/lxhshandian_org.gif", "喝多了": "a7/lxhheduole_org.gif", "收藏": "83/lxhshoucang_org.gif", "龙啸": "cd/lxhlongxiao_org.gif", "招财": "a9/lxhzhaocai_org.gif", "金元宝": "9b/lxhjinyuanbao_org.gif", "拜年了": "0c/lxhbainianle_org.gif", "福到啦": "f4/lxhfudaola_org.gif", "红包拿来": "bd/lxhhongbaonalai_org.gif", "放鞭炮": "bd/lxhbianpao_org.gif", "发红包": "27/lxhhongbao_org.gif", "大红灯笼": "90/lxhdahongdenglong_org.gif", "萌萌星星眼": "00/mmxingxingyan_org.gif", "萌萌打滚": "53/mmdagun_org.gif", "萌萌甩帽": "05/mmshuaimaozi_org.gif", "萌萌摔瓶": "d1/mmshuaipingzi_org.gif", "萌萌扭屁股": "4b/mmniupigu_org.gif", "萌萌惊讶": "96/mmjidujingya_org.gif", "萌萌懒得理": "81/mmlandeli_org.gif", "萌萌偷乐": "95/mmwuzuile_org.gif", "萌萌鄙视": "d1/mmbishini_org.gif", "萌萌哈欠": "c4/mmdagehaqian_org.gif", "萌萌石化": "c9/mmshihua_org.gif", "萌萌敲鼓": "d9/mmqiaodagu_org.gif", "萌萌叹气": "e4/mmtankouqi_org.gif", "萌萌捶地笑": "ff/mmchuidixiao_org.gif", "萌萌捂脸": "a7/mmwulian_org.gif", "萌萌流汗": "b8/mmkuangliuhan_org.gif", "萌萌抠鼻": "3e/mmkoubizi_org.gif", "萌萌泪奔": "1f/mmleiben_org.gif", "萌萌献花": "f3/mmxianduohua_org.gif", "bofu拜年": "0d/bofulongnian_org.gif", "bofu淫笑": "d2/bofuyinxiao_org.gif", "bofu压力山大": "64/bofuyalishanda_org.gif", "bofu心灰意冷": "77/bofuxinhuiyileng_org.gif", "bofu心动": "76/bofuxindong_org.gif", "bofu咸蛋超人": "6f/bofuxiandanchaoren_org.gif", "bofu食神": "52/bofushishen_org.gif", "bofu票子快来": "93/bofupiaozikuailai_org.gif", "bofu怒": "50/bofunu_org.gif", "bofu扭": "fb/bofuniu_org.gif", "bofu梦遗": "80/bofumengyi_org.gif", "bofu累": "ee/bofulei_org.gif", "bofu啃西瓜": "5a/bofukenxigua_org.gif", "bofu给力": "5c/bofugeili_org.gif", "bofu发愤图强": "71/bofufafentuqiang_org.gif", "bofu抖骚": "1f/bofudousao_org.gif", "bofu得瑟": "7e/bofudese_org.gif", "bofu打飞机": "37/bofudafeiji_org.gif", "bofu变脸": "bb/bofubianlian_org.gif", "bofu蹦极": "5e/bofubengji_org.gif", "bofu暴躁": "20/bofubaozao_org.gif", "bed蹬腿": "d5/brddengtui_org.gif", "bed嘿哈": "4c/brdheiha_org.gif", "bed拍手": "d6/brdpaishou_org.gif", "bed仰卧起坐": "44/brdyangwoqizuo_org.gif", "bed踏步": "72/brdtabu_org.gif", "bed飘忽": "9c/brdpiaohu_org.gif", "bed揉眼": "95/brdrouyan_org.gif", "bed挠痒": "f9/brdnaoyang_org.gif", "bed练腰": "bb/brdlianyao_org.gif", "bed举哑铃": "eb/brdjuyaling_org.gif", "bed啦啦啦": "a7/brdlalala_org.gif", "bed兴奋": "56/brdxingfen_org.gif", "bed出浴": "dc/brdchuyu_org.gif", "bed跑": "e9/brdpao_org.gif", "bed扯": "71/brdche_org.gif", "bed皮": "85/brdpi_org.gif", "bed转圈": "86/brdzhuanquan_org.gif", "bed凌乱": "fa/brdlingluan_org.gif", "bed奔跑": "fa/brdbenpao_org.gif", "bed飞吻": "d7/brdfeiwen_org.gif", "bed撒娇": "a1/brdsajiao_org.gif", "bed拍脸": "00/brdpailian_org.gif", "bed好饱": "f0/brdhaobao_org.gif", "bed跳": "bc/brdtiao_org.gif", "bed巴掌": "4e/brdbazhang_org.gif", "bed弹跳": "4d/brdtantiao_org.gif", "雾": "68/w_org.gif", "台风": "55/tf_org.gif", "沙尘暴": "69/sc_org.gif", "晴转多云": "d2/qzdy_org.gif", "流星": "8e/lx_org.gif", "龙卷风": "6a/ljf_org.gif", "洪水": "ba/hs2_org.gif", "风": "74/gf_org.gif", "多云转晴": "f3/dyzq_org.gif", "彩虹": "03/ch_org.gif", "冰雹": "05/bb2_org.gif", "微风": "a5/wind_org.gif", "阳光": "1a/sunny_org.gif", "雪": "00/snow_org.gif", "闪电": "e3/sh_org.gif", "下雨": "50/rain.gif", "阴天": "37/dark_org.gif", "鞭炮": "36/../23/bianpao_org.gif", "让红包飞": "c8/../e0/hongbao1_org.gif", "围脖": "3f/weijin_org.gif", "温暖帽子": "f1/wennuanmaozi_org.gif", "手套": "72/shoutao_org.gif", "红包": "71/hongbao_org.gif", "喜": "bf/xi_org.gif", "礼物": "c4/liwu_org.gif", "蛋糕": "6a/cake.gif", "钻戒": "31/r_org.gif", "钻石": "9f/diamond_org.gif", "大巴": "9c/dynamicbus_org.gif", "飞机": "6d/travel_org.gif", "自行车": "46/zxc_org.gif", "汽车": "a4/jc_org.gif", "手机": "4b/sj2_org.gif", "照相机": "33/camera_org.gif", "药": "5d/y_org.gif", "电脑": "df/dn_org.gif", "手纸": "55/sz_org.gif", "落叶": "79/yellowMood_org.gif", "圣诞树": "a2/christree_org.gif", "圣诞帽": "06/chrishat_org.gif", "圣诞老人": "c5/chrisfather_org.gif", "圣诞铃铛": "64/chrisbell_org.gif", "圣诞袜": "08/chrisocks_org.gif", "神龙": "34/longniao_org.gif", "龙蛋": "21/longdan_org.gif", "驯鹿": "0a/xunlu_org.gif", "上海志愿者": "21/shfabu_org.gif", "音乐盒": "79/yinyuehe_org.gif", "首发": "eb/shoufa_org.gif", "悼念乔布斯": "26/Jobs_org.gif", "iPhone": "19/iPhone_org.gif", "微博蛋糕": "e3/weibo2zhounian_org.png", "蜡烛": "91/lazu_org.gif", "康乃馨": "2e/muqinjie_org.png", "图片": "ce/tupianimage_org.gif", "植树节": "56/zhishujie_org.gif", "粉蛋糕": "bf/nycake_org.gif", "糖果": "34/candy_org.gif", "万圣节": "73/nanguatou2_org.gif", "火炬": "3b/hj_org.gif", "酒壶": "64/wine_org.gif", "月饼": "96/mooncake3_org.gif", "满月": "5d/moon1_org.gif", "巧克力": "b1/qkl_org.gif", "脚印": "12/jy_org.gif", "酒": "39/j2_org.gif", "狗": "5d/g_org.gif", "工作": "b2/gz3_org.gif", "档案": "ce/gz2_org.gif", "叶子": "b8/green_org.gif", "钢琴": "b2/gq_org.gif", "印迹": "84/foot_org.gif", "钟": "d3/clock_org.gif", "茶": "a8/cha_org.gif", "西瓜": "6b/watermelon.gif", "雨伞": "33/umb_org.gif", "电视机": "b3/tv_org.gif", "电话": "9d/tel_org.gif", "太阳": "e5/sun.gif", "星": "0b/star_org.gif", "哨子": "a0/shao.gif", "话筒": "1b/m_org.gif", "音乐": "d0/music_org.gif", "电影": "77/movie_org.gif", "月亮": "b9/moon.gif", "唱歌": "79/ktv_org.gif", "冰棍": "3a/ice.gif", "房子": "d1/house_org.gif", "帽子": "25/hat_org.gif", "足球": "c0/football.gif", "鲜花": "6c/flower_org.gif", "花": "6c/flower.gif", "风扇": "92/fan.gif", "干杯": "bd/cheer.gif", "咖啡": "64/cafe_org.gif", "拜年了": "0c/lxhbainianle_org.gif", "cc拜年": "63/longniancc_org.gif", "brd拜年": "46/brdlongnian_org.gif", "brd谨": "56/brdjinlongnian_org.gif", "brd贺": "a6/brdhelongnian_org.gif", "brd新": "82/brdxinlongnian_org.gif", "brd年": "55/brdnianlongnian_org.gif", "bofu拜年": "0d/bofulongnian_org.gif", "yz拜年": "5e/longnianyingzi_org.gif", "xyj拜年": "e3/longnianxyjbai_org.gif", "xyj红包": "d1/longnianxyjhb_org.gif", "xyj年年有鱼": "b1/longnianxyjyu_org.gif", "bobo拜年": "64/bobolongnian_org.gif", "toto拜年": "0b/longniantoto_org.gif", "dx拜年": "91/longniandx_org.gif", "nono拜年": "b3/longnianpanda_org.gif", "mtjj拜年": "5b/longnianmtjj_org.gif", "mk拜年": "7b/longnianmk_org.gif", "km拜年": "df/longniankm_org.gif", "alt拜年": "e9/longnianalt_org.gif", "xyj年年有鱼": "b1/longnianxyjyu_org.gif", "xyj拜年": "e3/longnianxyjbai_org.gif", "抓沙发": "63/chn_zhuashafa_org.gif", "震撼": "ae/chn_zhenhan_org.gif", "晕晕": "bd/chn_yun_org.gif", "坏笑": "79/chn_huaixiao_org.gif", "xyj红包": "d1/longnianxyjhb_org.gif", "瞎眼": "06/chn_xiayan_org.gif", "流汗": "99/chn_liuhan_org.gif", "冷": "48/chn_leng_org.gif", "老大": "90/chn_laoda_org.gif", "瞌睡": "60/chn_keshui_org.gif", "可怜的": "2b/chn_kelian_org.gif", "为难": "7f/chn_weinan_org.gif", "舔": "3a/chn_tian_org.gif", "j来嘛": "ed/xyjlaima_org.gif", "咖啡咖啡": "d7/chn_kafei_org.gif", "j媚眼": "84/xyjmeiyan_org.gif", "冲啊": "b5/chn_chonga_org.gif", "吃西瓜": "63/chn_chixigua_org.gif", "不要啊": "5e/chn_buyaoya_org.gif", "飙泪中": "04/chn_biaolei_org.gif", "爱你哦": "02/chn_aini_org.gif", "好得意": "9e/chn_deyi_org.gif", "顶啊": "c0/chn_ding_org.gif", "j疯了": "9c/xyjfengle_org.gif", "j浪笑": "aa/xyjlangxiao_org.gif", "j作揖": "74/xyjzuoyi_org.gif", "j哎呀": "c0/xyjaiya_org.gif", "j挂了": "b4/xyjguale_org.gif", "j扭秧歌": "8d/xyjniuyangge_org.gif", "j撒娇": "d9/xyjsajiao_org.gif", "j吐血": "57/xyjtuxue_org.gif", "j蹭": "65/xyjceng_org.gif", "ala吃货": "a5/altchihuo_org.gif", "ala上火": "1b/altshanghuo_org.gif", "ala囧": "b3/altjiong_org.gif", "ala哼": "cc/altheng_org.gif", "ala嘿嘿嘿": "94/altheiheihei_org.gif", "ala啊哈哈哈": "6a/altahahaha_org.gif", "ala么么": "ac/altmeme_org.gif", "ala扭啊扭": "8f/altniuaniu_org.gif", "ala衰": "7c/altshuai_org.gif", "ala讨厌": "43/alttaoyan_org.gif", "ala悲催": "f2/altbeicui_org.gif", "ala吐舌头": "3a/alttushetou_org.gif", "ala飘走": "33/altpiaozou_org.gif", "织": "41/zz2_org.gif", "兔子": "81/rabbit_org.gif", "神马": "60/horse2_org.gif", "浮云": "bc/fuyun_org.gif", "给力": "c9/geili_org.gif", "萌": "42/kawayi_org.gif", "鸭梨": "bb/pear_org.gif", "熊猫": "6e/panda_org.gif", "互粉": "89/hufen_org.gif", "围观": "f2/wg_org.gif", "扔鸡蛋": "91/rjd_org.gif", "奥特曼": "bc/otm_org.gif", "威武": "70/vw_org.gif", "伤心": "ea/unheart.gif", "热吻": "60/rw_org.gif", "囧": "15/j_org.gif", "orz": "c0/orz1_org.gif", "宅": "d7/z_org.gif", "小丑": "6b/xc_org.gif", "帅": "36/s2_org.gif", "猪头": "58/pig.gif", "实习": "48/sx_org.gif", "骷髅": "bd/kl2_org.gif", "便便": "34/s_org.gif", "雪人": "d9/xx2_org.gif", "黄牌": "a0/yellowcard.gif", "红牌": "64/redcard.gif", "跳舞花": "70/twh_org.gif", "礼花": "3d/bingo_org.gif", "打针": "b0/zt_org.gif", "叹号": "3b/th_org.gif", "问号": "9d/wh_org.gif", "句号": "9b/jh_org.gif", "逗号": "cc/dh_org.gif", "闪": "ce/03_org.gif", "啦啦": "c1/04_org.gif", "吼吼": "34/05_org.gif", "庆祝": "67/06_org.gif", "嘿": "d3/01_org.gif", "22": "43/twot_org.gif", "00": "3a/zero_org.gif", "2": "61/two_org.gif", "3": "78/three_org.gif", "6": "bf/six_org.gif", "7": "32/seven_org.gif", "1": "82/one_org.gif", "9": "54/nine_org.gif", "4": "72/four_org.gif", "5": "f5/five_org.gif", "8": "5c/eight_org.gif", "女孩儿": "1b/kissgirl_org.gif", "男孩儿": "4e/kissboy_org.gif", "z": "b2/newz_org.gif", "y": "3b/newy_org.gif", "x": "d7/newx_org.gif", "v": "e3/newv_org.gif", "u": "b8/newu_org.gif", "t": "75/newt_org.gif", "s": "22/news_org.gif", "r": "0c/newr_org.gif", "q": "de/newq_org.gif", "p": "e7/newp_org.gif", "n": "e7/newn_org.gif", "l": "f5/newl_org.gif", "k": "a0/newk_org.gif", "j": "af/newj_org.gif", "h": "8b/newh_org.gif", "g": "16/newg_org.gif", "f": "07/newf_org.gif", "d": "d8/newd_org.gif", "a": "32/newa_org.gif", "w": "94/weibow_org.gif", "点": "fd/weibop_org.gif", "o": "f5/weiboo_org.gif", "m": "98/weibom_org.gif", "i": "e6/weiboi_org.gif", "e": "dd/weiboe_org.gif", "c": "59/weiboc_org.gif", "b": "fa/weibob_org.gif", "省略号": "0d/shengluehao_org.gif", "kiss": "59/kiss2_org.gif", "圆": "53/yuan_org.gif", "团": "11/tuan_org.gif", "toto拜年": "0b/longniantoto_org.gif", "bobo拜年": "64/bobolongnian_org.gif", "toto无聊": "4a/totowuliao_org.gif", "toto我最摇滚": "53/totowozuiyaogun_org.gif", "toto数落": "04/totoshuluo_org.gif", "toto睡觉": "cb/totoshuijiao_org.gif", "toto甩头发": "34/totoshuaitoufa_org.gif", "toto飘过": "74/totopiaoguo_org.gif", "toto狂汗": "c9/totokuanghan_org.gif", "toto好累": "30/totohaolei_org.gif", "bobo抓狂": "8d/bobozhuakuang_org.gif", "bobo疑问": "a3/boboyiwen_org.gif", "bobo抛媚眼": "74/bobopaomeiyan_org.gif", "bobo膜拜": "af/bobomobai_org.gif", "bobo纠结": "f0/bobojiujie_org.gif", "bobo不要啊": "d0/bobobuyaoa_org.gif", "bobo不理你": "98/bobobulini_org.gif", "有爱": "b9/totoyouai_org.gif", "气死了": "b2/totoyes_org.gif", "我爱听": "02/tototingge_org.gif", "怒火": "af/totonu_org.gif", "擂鼓": "bd/totoleigu_org.gif", "讥笑": "d8/totojixiao_org.gif", "抛钱": "37/totoheixianpaoqian_org.gif", "变花": "72/boboxianhua_org.gif", "飙泪": "7f/boboweiqu_org.gif", "藏猫猫": "18/bobotoukan_org.gif", "淘气": "9e/bobotiaopi_org.gif", "生闷气": "47/boboshengmenqi_org.gif", "忍": "a7/boboren_org.gif", "泡泡糖": "a5/bobopaopaotang_org.gif", "好的": "e0/bobook_org.gif", "Hi": "44/bobohi_org.gif", "飞吻": "79/bobofeiwen_org.gif", "我爱西瓜": "29/bobochixigua_org.gif", "吓一跳": "ce/bobochijing_org.gif", "吃饭": "87/bobochifan_org.gif", "dx拜年": "91/longniandx_org.gif", "dx炸弹": "78/daxiongzhadan_org.gif", "dx洗澡": "07/daxiongxizao_org.gif", "dx握爪": "ff/daxiongwozhua_org.gif", "dx数落": "4f/daxiongshuluo_org.gif", "dx刷牙": "f5/daxiongshuaya_org.gif", "dx傻": "aa/daxiongsha_org.gif", "dx晒": "c4/daxiongshai_org.gif", "dx抛媚眼": "45/daxiongpaomeiyan_org.gif", "dx拍拍手": "7b/daxiongpaipaishou_org.gif", "dx耶": "10/daxiongoye_org.gif", "dx扭": "00/daxiongniu_org.gif", "dx没有": "7f/daxiongmeiyou_org.gif", "dx卖萌": "51/daxiongmaimeng_org.gif", "dx脸红": "b7/daxionglianhong_org.gif", "dx泪奔": "ca/daxiongleibenxiong_org.gif", "dx加油": "d7/daxiongjiayouxiong_org.gif", "dx脚踏车": "6a/daxiongjiaotache_org.gif", "dx花心": "b9/daxionghuaxin_org.gif", "dx欢乐": "01/daxionghuanle_org.gif", "dx滑板": "9f/daxionghuaban_org.gif", "dx倒": "57/daxiongdao_org.gif", "dx超人": "70/daxiongchaoren_org.gif", "dx饱": "27/daxiongbao_org.gif", "dx哎": "da/daxiongai_org.gif", "欢欢": "c3/liaobuqi_org.gif", "乐乐": "66/guanbuzhao_org.gif", "管不着爱": "78/2guanbuzhao1_org.gif", "爱": "09/ai_org.gif", "了不起爱": "11/2liaobuqiai_org.gif", "gbz真穿越": "2a/gbzzhenchuanyue_org.gif", "gbz再睡会": "73/gbzzaishuihui_org.gif", "gbz呜呜": "c6/gbzwuwu_org.gif", "gbz委屈": "74/gbzweiqu_org.gif", "gbz晚安了": "79/gbzwananle_org.gif", "gbz祈福": "4e/gbzqifu_org.gif", "gbz祈福了": "96/gbzqifule_org.gif", "gbz窃笑": "57/gbzqiexiao_org.gif", "gbz起床啦": "8d/gbzqichuangla_org.gif", "gbz困": "f5/gbzkun_org.gif", "gbz加班": "53/gbzjiaban_org.gif", "gbz加班中": "53/gbzjiabanzhong_org.gif", "gbz饿": "50/gbze_org.gif", "gbz饿晕": "e4/gbzeyun_org.gif", "gbz得意": "0a/gbzdeyi_org.gif", "gbz大笑": "f7/gbzdaxiao_org.gif", "gbz穿越了": "16/gbzchuanyuele_org.gif", "有点困": "68/youdiankun_org.gif", "yes": "9e/yes_org.gif", "咽回去了": "72/yanhuiqule_org.gif", "鸭梨很大": "01/yalihenda_org.gif", "羞羞": "42/xiuxiu_org.gif", "喜欢你": "6b/xihuang_org.gif", "小便屁": "a0/xiaobianpi_org.gif", "无奈": "d6/wunai22_org.gif", "兔兔": "da/tutu_org.gif", "吐舌头": "98/tushetou_org.gif", "头晕": "48/touyun_org.gif", "听音乐": "d3/tingyinyue_org.gif", "睡大觉": "65/shuijiao_org.gif", "闪闪紫": "9e/shanshanzi_org.gif", "闪闪绿": "a8/shanshanlu_org.gif", "闪闪灰": "1e/shanshanhui_org.gif", "闪闪红": "10/shanshanhong_org.gif", "闪闪粉": "9d/shanshanfen_org.gif", "咆哮": "4b/paoxiao_org.gif", "摸头": "2c/motou_org.gif", "真美好": "d2/meihao_org.gif", "脸红自爆": "d8/lianhongzibao_org.gif", "哭泣女": "1c/kuqinv_org.gif", "哭泣男": "38/kuqinan_org.gif", "空": "fd/kong_org.gif", "尽情玩": "9f/jinqingwan_org.gif", "惊喜": "b8/jingxi_org.gif", "惊呆": "58/jingdai_org.gif", "胡萝卜": "e1/huluobo_org.gif", "欢腾去爱": "63/huangtengquai_org.gif", "感冒了": "67/ganmao_org.gif", "怒了": "ef/fennu_org.gif", "我要奋斗": "a6/fendou123_org.gif", "发芽": "95/faya_org.gif", "春暖花开": "ca/chunnuanhuakai_org.gif", "抽烟": "83/chouyan_org.gif", "昂": "31/ang_org.gif", "啊": "12/aa_org.gif", "自插双目": "d3/zichashuangmu_org.gif", "咦": "9f/yiwen_org.gif", "嘘嘘": "cf/xu_org.gif", "我吃": "00/wochiwode_org.gif", "喵呜": "a7/weiqu_org.gif", "v5": "c5/v5_org.gif", "调戏": "f7/tiaoxi_org.gif", "打牙": "d7/taihaoxiaole_org.gif", "手贱": "b8/shoujian_org.gif", "色": "a1/se_org.gif", "喷": "4a/pen_org.gif", "你懂的": "2e/nidongde_org.gif", "喵": "a0/miaomiao_org.gif", "美味": "c1/meiwei_org.gif", "惊恐": "46/jingkong_org.gif", "感动": "7c/gandong_org.gif", "放开": "55/fangkai_org.gif", "痴呆": "e8/chidai_org.gif", "扯脸": "99/chelian_org.gif", "不知所措": "ab/buzhisuocuo_org.gif", "白眼": "24/baiyan_org.gif", "ali做鬼脸": "3c/alizuoguilian_org.gif", "ali追": "67/alizhui_org.gif", "ali转": "c1/alizhuan_org.gif", "ali转圈哭": "40/alizhuanquanku_org.gif", "ali郁闷": "3a/aliyumen_org.gif", "ali元宝": "a1/aliyuanbao_org.gif", "ali摇晃": "21/aliyaohuang_org.gif", "ali嘘嘘嘘": "ff/alixuxuxu_org.gif", "ali羞": "53/alixiu_org.gif", "ali吓": "0e/alixia_org.gif", "ali笑": "55/alixiao_org.gif", "ali掀桌子": "ae/alixianzhuo_org.gif", "ali献花": "27/alixianhua_org.gif", "ali想": "19/alixiang_org.gif", "ali哇": "67/aliwa_org.gif", "ali吐血": "89/alituxue_org.gif", "ali偷看": "3a/alitoukan_org.gif", "ali送礼物": "21/alisongliwu_org.gif", "ali水": "5b/alishui_org.gif", "ali摔": "1f/alishuai_org.gif", "ali甩手": "d0/alishuaishou_org.gif", "ali撒钱": "d5/alisaqian_org.gif", "ali亲一个": "8e/aliqinyige_org.gif", "ali欠揍": "e9/aliqianzou_org.gif", "ali扑": "50/alipu_org.gif", "ali扑倒": "54/alipudao_org.gif", "ali飘": "52/alipiao_org.gif", "ali飘过": "b2/alipiaoguo_org.gif", "ali喷嚏": "af/alipenti_org.gif", "ali拍拍手": "01/alipaipaishou_org.gif", "ali你": "ba/alini_org.gif", "ali挠墙": "83/alinaoqiang_org.gif", "ali摸摸头": "67/alimomotou_org.gif", "ali溜": "48/aliliu_org.gif", "ali赖皮": "dd/alilaipi_org.gif", "ali来吧": "ca/alilaiba_org.gif", "ali揪": "8d/alijiu_org.gif", "ali囧": "cd/alijiong_org.gif", "ali惊": "cd/alijing_org.gif", "ali加油": "ae/alijiayou_org.gif", "ali僵尸跳": "72/alijiangshitiao_org.gif", "ali呼啦圈": "cd/alihulaquan_org.gif", "ali画圈圈": "a7/alihuaquanquan_org.gif", "ali欢呼": "5e/alihuanhu_org.gif", "ali坏笑": "3a/alihuaixiao_org.gif", "ali跪求": "5a/aliguiqiu_org.gif", "ali风筝": "7b/alifengzheng_org.gif", "ali飞": "75/alifei_org.gif", "ali翻白眼": "75/alifanbaiyan_org.gif", "ali顶起": "e6/alidingqi_org.gif", "ali点头": "d0/alidiantou_org.gif", "ali得瑟": "65/alidese_org.gif", "ali打篮球": "c6/alidalanqiu_org.gif", "ali打滚": "ec/alidagun_org.gif", "ali大吃": "06/alidachi_org.gif", "ali踩": "6b/alicai_org.gif", "ali不耐烦": "32/alibunaifan_org.gif", "ali不嘛": "0c/alibuma_org.gif", "ali别吵": "51/alibiechao_org.gif", "ali鞭炮": "35/alibianpao_org.gif", "ali抱一抱": "a8/alibaoyibao_org.gif", "ali拜年": "e3/alibainian_org.gif", "ali88": "56/ali88_org.gif", "ali笑死了": "69/ali233_org.gif", "狂笑": "d5/zk_org.gif", "冤": "5f/wq2_org.gif", "蜷": "87/q2_org.gif", "美好": "ae/mh_org.gif", "乐和": "5f/m2_org.gif", "揪耳朵": "15/j3_org.gif", "晃": "bf/h2_org.gif", "high": "e7/f_org.gif", "蹭": "33/c_org.gif", "抱枕": "f4/bz3_org.gif", "不公平": "85/bgp_org.gif", "mk拜年": "7b/longnianmk_org.gif", "真淡定": "61/cat_zhendanding_org.gif", "运气中": "c3/cat_yunqizhong_org.gif", "嗯": "03/cat_yi_org.gif", "一头竖线": "bb/cat_yitoushuxian_org.gif", "星星眼儿": "9c/cat_xingxingyan_org.gif", "笑眯眯": "26/cat_xiaomimi_org.gif", "小地主": "be/cat_xiaodizhu_org.gif", "我错了": "54/cat_wocuole_org.gif", "喂": "63/cat_wei_org.gif", "伸舌头": "21/cat_tushetou_org.gif", "天然呆": "e2/cat_tianrandai_org.gif", "陶醉了": "8d/cat_taozuile_org.gif", "生气了": "39/cat_shengqile_org.gif", "生病鸟": "06/cat_shengbingle_org.gif", "忍不了": "9c/cat_renbuliao_org.gif", "扑克脸": "05/cat_pukelian_org.gif", "瀑布汗": "22/cat_pubuhan_org.gif", "你没事吧": "3d/cat_nimeishiba_org.gif", "内牛满面": "68/cat_neiniumanmian_org.gif", "没听见": "62/cat_meitingjian_org.gif", "哭死啦": "30/cat_kusila_org.gif", "囧汗": "21/cat_jionghan_org.gif", "惊恐中": "f8/cat_jingkongzhong_org.gif", "混乱中": "e8/cat_hunluanzhong_org.gif", "花痴闪闪": "4e/cat_huachishanshan_org.gif", "嘿嘿嘿": "93/cat_heiheihei_org.gif", "哈哈哈哈": "b9/cat_hahaha_org.gif", "干笑中": "4e/cat_ganxiaozhong_org.gif", "恶心死": "c5/cat_exinsi_org.gif", "嘟嘟嘴": "48/cat_duduzui_org.gif", "大怒": "d9/cat_danu_org.gif", "大惊失色": "55/cat_dajingshise_org.gif", "呆呆": "c2/cat_daidai_org.gif", "搭错线": "94/cat_dacuoxian_org.gif", "鼻涕虫": "15/cat_bitichong_org.gif", "暴雨汗": "e2/cat_baoyuhan_org.gif", "啊呜啊呜": "f4/cat_awuawu_org.gif", "哇": "22/cat_ai_org.gif", "爱爱爱": "ac/cat_aiaiai_org.gif", "猥琐": "e1/weisuo_org.gif", "挑眉": "c9/tiaomei_org.gif", "挑逗": "3c/tiaodou_org.gif", "亲耳朵": "1c/qinerduo_org.gif", "媚眼": "32/meiyan_org.gif", "冒个泡": "32/maogepao_org.gif", "囧耳朵": "f0/jiongerduo_org.gif", "鬼脸": "14/guilian_org.gif", "放电": "fd/fangdian_org.gif", "悲剧": "ea/beiju_org.gif", "抚摸": "78/touch_org.gif", "大汗": "13/sweat_org.gif", "大惊": "74/suprise_org.gif", "惊哭": "0c/supcry_org.gif", "星星眼": "5c/stareyes_org.gif", "好困": "8b/sleepy_org.gif", "呕吐": "75/sick_org.gif", "加我一个": "ee/plus1_org.gif", "痞痞兔耶": "19/pipioye_org.gif", "mua": "c6/muamua_org.gif", "面抽": "fd/mianchou_org.gif", "大笑": "6a/laugh_org.gif", "揉": "d6/knead_org.gif", "痞痞兔囧": "38/jiong_org.gif", "哈尼兔耶": "53/honeyoye_org.gif", "开心": "40/happy_org.gif", "咬手帕": "af/handkerchief_org.gif", "去": "6b/go_org.gif", "晕死了": "a4/dizzy_org.gif", "大哭": "af/cry_org.gif", "扇子遮面": "a1/coverface_org.gif", "怒气": "ea/angery_org.gif", "886": "6f/886_org.gif", "白羊": "07/byz2_org.gif", "射手": "46/ssz2_org.gif", "双鱼": "e2/syz2_org.gif", "双子": "89/szz2_org.gif", "天秤": "6b/tpz2_org.gif", "天蝎": "1e/txz2_org.gif", "水瓶": "1b/spz2_org.gif", "处女": "62/cnz2_org.gif", "金牛": "3b/jnz2_org.gif", "巨蟹": "d2/jxz2_org.gif", "狮子": "4a/leo2_org.gif", "摩羯": "16/mjz2_org.gif", "天蝎座": "09/txz_org.gif", "天秤座": "c1/tpz_org.gif", "双子座": "d4/szz_org.gif", "双鱼座": "7f/syz_org.gif", "射手座": "5d/ssz_org.gif", "水瓶座": "00/spz_org.gif", "摩羯座": "da/mjz_org.gif", "狮子座": "23/leo_org.gif", "巨蟹座": "a3/jxz_org.gif", "金牛座": "8d/jnz_org.gif", "处女座": "09/cnz_org.gif", "白羊座": "e0/byz_org.gif", "爱心传递": "b8/aixincd_org.gif", "绿丝带": "9b/green_band_org.gif", "粉红丝带": "77/pink_org.gif", "红丝带": "59/red_band_org.gif", "加油": "d4/jiayou_org.gif", "国旗": "dc/flag_org.gif", "金牌": "f4/jinpai_org.gif", "银牌": "1e/yinpai_org.gif", "铜牌": "26/tongpai_org.gif", "哨子": "a0/shao.gif", "黄牌": "a0/yellowcard.gif", "红牌": "64/redcard.gif", "足球": "c0/football.gif", "篮球": "2c/bball_org.gif", "黑8": "6b/black8_org.gif", "排球": "cf/volleyball_org.gif", "游泳": "b9/swimming_org.gif", "乒乓球": "a5/pingpong_org.gif", "投篮": "7a/basketball_org.gif", "羽毛球": "77/badminton_org.gif", "射门": "e0/zuqiu_org.gif", "射箭": "40/shejian_org.gif", "举重": "14/juzhong_org.gif", "微微笑": "9a/xiaoheweixiao_org.gif", "特委屈": "02/xiaoheweiqu_org.gif", "我吐": "c1/xiaohetua_org.gif", "很生气": "66/xiaoheshengqi_org.gif", "流鼻涕": "08/xiaoheliubiti_org.gif", "默默哭泣": "a0/xiaohekuqi_org.gif", "小盒汗": "e3/xiaohehan_org.gif", "发呆中": "44/xiaohefadai_org.gif", "不理你": "a8/xiaohebulini_org.gif", "强烈鄙视": "d4/xiaohebishi_org.gif", "烦躁": "c5/fanzao_org.gif", "呲牙": "c1/ciya_org.gif", "有钱": "e6/youqian_org.gif", "微笑": "05/weixiao_org.gif", "帅爆": "c1/shuaibao_org.gif", "生气": "0a/shengqi_org.gif", "生病了": "19/shengbing_org.gif", "色眯眯": "90/semimi_org.gif", "疲劳": "d1/pilao_org.gif", "瞄": "14/miao_org.gif", "哭": "79/ku_org.gif", "好可怜": "76/kelian_org.gif", "紧张": "75/jinzhang_org.gif", "惊讶": "dc/jingya_org.gif", "激动": "bb/jidong_org.gif", "见钱": "2b/jianqian_org.gif", "汗了": "7d/han_org.gif", "奋斗": "4e/fendou_org.gif", "小人得志": "09/xrdz_org.gif", "哇哈哈": "cc/whh_org.gif", "叹气": "90/tq_org.gif", "冻结": "d3/sjdj_org.gif", "切": "1d/q_org.gif", "拍照": "ec/pz_org.gif", "怕怕": "7c/pp_org.gif", "怒吼": "4d/nh_org.gif", "膜拜": "9f/mb2_org.gif", "路过": "70/lg_org.gif", "泪奔": "34/lb_org.gif", "脸变色": "cd/lbs_org.gif", "亲": "05/kiss_org.gif", "恐怖": "86/kb_org.gif", "交给我吧": "e2/jgwb_org.gif", "欢欣鼓舞": "2b/hxgw_org.gif", "高兴": "c7/gx3_org.gif", "尴尬": "43/gg_org.gif", "发嗲": "4e/fd_org.gif", "犯错": "19/fc_org.gif", "得意": "fb/dy_org.gif", "吵闹": "fa/cn_org.gif", "冲锋": "2f/cf_org.gif", "抽耳光": "eb/ceg_org.gif", "差得远呢": "ee/cdyn_org.gif", "被砸": "5a/bz2_org.gif", "拜托": "6e/bt_org.gif", "必胜": "cf/bs3_org.gif", "不关我事": "e8/bgws_org.gif", "上火": "64/bf_org.gif", "不倒翁": "b6/bdw_org.gif", "不错哦": "79/bco_org.gif", "yeah": "1a/yeah_org.gif", "喜欢": "5f/xh_org.gif", "心动": "5f/xd_org.gif", "无聊": "53/wl_org.gif", "手舞足蹈": "b2/gx_org.gif", "搞笑": "09/gx2_org.gif", "痛哭": "eb/gd_org.gif", "爆发": "38/fn2_org.gif", "发奋": "31/d2_org.gif", "不屑": "b0/bx_org.gif", "眨眨眼": "3b/zy2_org.gif", "杂技": "ec/zs_org.gif", "多问号": "17/wh2_org.gif", "跳绳": "79/ts_org.gif", "强吻": "b1/q3_org.gif", "不活了": "37/lb2_org.gif", "磕头": "6a/kt_org.gif", "呜呜": "55/bya_org.gif", "不": "a2/bx2_org.gif"

// 繁体只能手动维护  
, "織":"41/zz2_org.gif","神馬":"60/horse2_org.gif","浮雲":"bc/fuyun_org.gif","給力":"c9/geili_org.gif","圍觀":"f2/wg_org.gif","威武":"70/vw_org.gif","熊貓":"6e/panda_org.gif","兔子":"81/rabbit_org.gif","奧特曼":"bc/otm_org.gif","囧":"15/j_org.gif","互粉":"89/hufen_org.gif","禮物":"c4/liwu_org.gif","呵呵":"ac/smilea_org.gif","嘻嘻":"0b/tootha_org.gif","哈哈":"6a/laugh.gif","可愛":"14/tza_org.gif","可憐":"af/kl_org.gif","挖鼻屎":"a0/kbsa_org.gif","吃驚":"f4/cj_org.gif","害羞":"6e/shamea_org.gif","擠眼":"c3/zy_org.gif","閉嘴":"29/bz_org.gif","鄙視":"71/bs2_org.gif","愛你":"6d/lovea_org.gif","淚":"9d/sada_org.gif","偷笑":"19/heia_org.gif","親親":"8f/qq_org.gif","生病":"b6/sb_org.gif","太開心":"58/mb_org.gif","懶得理你":"17/ldln_org.gif","右哼哼":"98/yhh_org.gif","左哼哼":"6d/zhh_org.gif","噓":"a6/x_org.gif","衰":"af/cry.gif","委屈":"73/wq_org.gif","吐":"9e/t_org.gif","打哈氣":"f3/k_org.gif","抱抱":"27/bba_org.gif","怒":"7c/angrya_org.gif","疑問":"5c/yw_org.gif","饞嘴":"a5/cza_org.gif","拜拜":"70/88_org.gif","思考":"e9/sk_org.gif","汗":"24/sweata_org.gif","困":"7f/sleepya_org.gif","睡覺":"6b/sleepa_org.gif","錢":"90/money_org.gif","失望":"0c/sw_org.gif","酷":"40/cool_org.gif","花心":"8c/hsa_org.gif","哼":"49/hatea_org.gif","鼓掌":"36/gza_org.gif","暈":"d9/dizzya_org.gif","悲傷":"1a/bs_org.gif","抓狂":"62/crazya_org.gif","黑線":"91/h_org.gif","陰險":"6d/yx_org.gif","怒駡":"89/nm_org.gif","心":"40/hearta_org.gif","傷心":"ea/unheart.gif","豬頭":"58/pig.gif","ok":"d6/ok_org.gif","耶":"d9/ye_org.gif","good":"d8/good_org.gif","不要":"c7/no_org.gif","贊":"d0/z2_org.gif","來":"40/come_org.gif","弱":"d8/sad_org.gif","蠟燭":"91/lazu_org.gif","鐘":"d3/clock_org.gif","蛋糕":"6a/cake.gif","話筒":"1b/m_org.gif","握手":"0c/ws_org.gif","溫暖帽子":"f1/wennuanmaozi_org.gif","手套":"72/shoutao_org.gif","圍脖":"3f/weijin_org.gif","聖誕樹":"a2/christree_org.gif","聖誕帽":"06/chrishat_org.gif","藥":"5d/y_org.gif","落葉":"79/yellowMood_org.gif","禮花":"3d/bingo_org.gif","淘氣":"9e/bobotiaopi_org.gif","有愛":"b9/totoyouai_org.gif","好可憐":"76/kelian_org.gif","呲牙":"c1/ciya_org.gif","擠眼":"c3/zy_org.gif","親親":"8f/qq_org.gif","怒罵":"89/nm_org.gif","太開心":"58/mb_org.gif","懶得理你":"17/ldln_org.gif","打哈氣":"f3/k_org.gif","生病":"b6/sb_org.gif","書呆子":"61/sdz_org.gif","失望":"0c/sw_org.gif","可憐":"af/kl_org.gif","黑線":"91/h_org.gif","吐":"9e/t_org.gif","委屈":"73/wq_org.gif","思考":"e9/sk_org.gif","哈哈":"6a/laugh.gif","噓":"a6/x_org.gif","右哼哼":"98/yhh_org.gif","左哼哼":"6d/zhh_org.gif","疑問":"5c/yw_org.gif","陰險":"6d/yx_org.gif","頂":"91/d_org.gif","錢":"90/money_org.gif","悲傷":"1a/bs_org.gif","鄙視":"71/bs2_org.gif","拜拜":"70/88_org.gif","吃驚":"f4/cj_org.gif","閉嘴":"29/bz_org.gif","衰":"af/cry.gif","憤怒":"bd/fn_org.gif","感冒":"a0/gm_org.gif","酷":"40/cool_org.gif","來":"40/come_org.gif","good":"d8/good_org.gif","haha":"13/ha_org.gif","不要":"c7/no_org.gif","ok":"d6/ok_org.gif","拳頭":"cc/o_org.gif","弱":"d8/sad_org.gif","握手":"0c/ws_org.gif","贊":"d0/z2_org.gif","最差":"3e/bad_org.gif","可愛":"14/tza_org.gif","嘻嘻":"0b/tootha_org.gif","汗":"24/sweata_org.gif","呵呵":"ac/smilea_org.gif","困":"7f/sleepya_org.gif","睡覺":"6b/sleepa_org.gif","害羞":"6e/shamea_org.gif","淚":"9d/sada_org.gif","愛你":"6d/lovea_org.gif","挖鼻屎":"a0/kbsa_org.gif","花心":"8c/hsa_org.gif","偷笑":"19/heia_org.gif","心":"40/hearta_org.gif","哼":"49/hatea_org.gif","鼓掌":"36/gza_org.gif","暈":"d9/dizzya_org.gif","饞嘴":"a5/cza_org.gif","抓狂":"62/crazya_org.gif","抱抱":"27/bba_org.gif","怒":"7c/angrya_org.gif","右抱抱":"0d/right_org.gif","左抱抱":"54/left_org.gif","有愛":"b9/totoyouai_org.gif","氣死了":"b2/totoyes_org.gif","我愛聽":"02/tototingge_org.gif","怒火":"af/totonu_org.gif","擂鼓":"bd/totoleigu_org.gif","譏笑":"d8/totojixiao_org.gif","拋錢":"37/totoheixianpaoqian_org.gif","變花":"72/boboxianhua_org.gif","飆淚":"7f/boboweiqu_org.gif","藏貓貓":"18/bobotoukan_org.gif","淘氣":"9e/bobotiaopi_org.gif","生悶氣":"47/boboshengmenqi_org.gif","忍":"a7/boboren_org.gif","泡泡糖":"a5/bobopaopaotang_org.gif","好的":"e0/bobook_org.gif","Hi":"44/bobohi_org.gif","飛吻":"79/bobofeiwen_org.gif","我愛西瓜":"29/bobochixigua_org.gif","嚇一跳":"ce/bobochijing_org.gif","吃飯":"87/bobochifan_org.gif","圍脖":"3f/weijin_org.gif","溫暖帽子":"f1/wennuanmaozi_org.gif","手套":"72/shoutao_org.gif","紅包":"71/hongbao_org.gif","喜":"bf/xi_org.gif","禮物":"c4/liwu_org.gif","蛋糕":"6a/cake.gif","鑽戒":"31/r_org.gif","鑽石":"9f/diamond_org.gif","大巴":"9c/dynamicbus_org.gif","飛機":"6d/travel_org.gif","自行車":"46/zxc_org.gif","汽車":"a4/jc_org.gif","手機":"4b/sj2_org.gif","照相機":"33/camera_org.gif","藥":"5d/y_org.gif","電腦":"df/dn_org.gif","手紙":"55/sz_org.gif","落葉":"79/yellowMood_org.gif","聖誕樹":"a2/christree_org.gif","聖誕帽":"06/chrishat_org.gif","聖誕老人":"c5/chrisfather_org.gif","聖誕鈴鐺":"64/chrisbell_org.gif","聖誕襪":"08/chrisocks_org.gif","音樂盒":"79/yinyuehe_org.gif","首發":"eb/shoufa_org.gif","悼念喬佈斯":"26/Jobs_org.gif","iPhone":"19/iPhone_org.gif","微博蛋糕":"e3/weibo2zhounian_org.png","蠟燭":"91/lazu_org.gif","康乃馨":"2e/muqinjie_org.png","圖片":"ce/tupianimage_org.gif","植樹節":"56/zhishujie_org.gif","粉蛋糕":"bf/nycake_org.gif","糖果":"34/candy_org.gif","萬聖節":"73/nanguatou2_org.gif","火炬":"3b/hj_org.gif","酒壺":"64/wine_org.gif","月餅":"96/mooncake3_org.gif","滿月":"5d/moon1_org.gif","巧克力":"b1/qkl_org.gif","腳印":"12/jy_org.gif","酒":"39/j2_org.gif","狗":"5d/g_org.gif","工作":"b2/gz3_org.gif","檔案":"ce/gz2_org.gif","葉子":"b8/green_org.gif","鋼琴":"b2/gq_org.gif","印跡":"84/foot_org.gif","鐘":"d3/clock_org.gif","茶":"a8/cha_org.gif","西瓜":"6b/watermelon.gif","雨傘":"33/umb_org.gif","電視機":"b3/tv_org.gif","電話":"9d/tel_org.gif","太陽":"e5/sun.gif","星":"0b/star_org.gif","哨子":"a0/shao.gif","話筒":"1b/m_org.gif","音樂":"d0/music_org.gif","電影":"77/movie_org.gif","月亮":"b9/moon.gif","唱歌":"79/ktv_org.gif","冰棍":"3a/ice.gif","房子":"d1/house_org.gif","帽子":"25/hat_org.gif","足球":"c0/football.gif","花":"6c/flower.gif","風扇":"92/fan.gif","乾杯":"bd/cheer.gif","咖啡":"64/cafe_org.gif","織":"41/zz2_org.gif","兔子":"81/rabbit_org.gif","神馬":"60/horse2_org.gif","浮雲":"bc/fuyun_org.gif","給力":"c9/geili_org.gif","萌":"42/kawayi_org.gif","鴨梨":"bb/pear_org.gif","熊貓":"6e/panda_org.gif","互粉":"89/hufen_org.gif","圍觀":"f2/wg_org.gif","扔雞蛋":"91/rjd_org.gif","奧特曼":"bc/otm_org.gif","威武":"70/vw_org.gif","傷心":"ea/unheart.gif","熱吻":"60/rw_org.gif","囧":"15/j_org.gif","orz":"c0/orz1_org.gif","宅":"d7/z_org.gif","小丑":"6b/xc_org.gif","帥":"36/s2_org.gif","豬頭":"58/pig.gif","實習":"48/sx_org.gif","骷髏":"bd/kl2_org.gif","便便":"34/s_org.gif","雪人":"d9/xx2_org.gif","黃牌":"a0/yellowcard.gif","紅牌":"64/redcard.gif","跳舞花":"70/twh_org.gif","禮花":"3d/bingo_org.gif","打針":"b0/zt_org.gif","嘆號":"3b/th_org.gif","問號":"9d/wh_org.gif","句號":"9b/jh_org.gif","逗號":"cc/dh_org.gif","閃":"ce/03_org.gif","啦啦":"c1/04_org.gif","吼吼":"34/05_org.gif","慶祝":"67/06_org.gif","嘿":"d3/01_org.gif","00":"3a/zero_org.gif","2":"61/two_org.gif","3":"78/three_org.gif","6":"bf/six_org.gif","7":"32/seven_org.gif","1":"82/one_org.gif","9":"54/nine_org.gif","4":"72/four_org.gif","5":"f5/five_org.gif","8":"5c/eight_org.gif","女孩兒":"1b/kissgirl_org.gif","男孩兒":"4e/kissboy_org.gif","z":"b2/newz_org.gif","y":"3b/newy_org.gif","x":"d7/newx_org.gif","v":"e3/newv_org.gif","u":"b8/newu_org.gif","t":"75/newt_org.gif","s":"22/news_org.gif","r":"0c/newr_org.gif","q":"de/newq_org.gif","p":"e7/newp_org.gif","n":"e7/newn_org.gif","l":"f5/newl_org.gif","k":"a0/newk_org.gif","j":"af/newj_org.gif","h":"8b/newh_org.gif","g":"16/newg_org.gif","f":"07/newf_org.gif","d":"d8/newd_org.gif","a":"32/newa_org.gif","w":"94/weibow_org.gif","點":"fd/weibop_org.gif","o":"f5/weiboo_org.gif","m":"98/weibom_org.gif","i":"e6/weiboi_org.gif","c":"59/weiboc_org.gif","b":"fa/weibob_org.gif","省略號":"0d/shengluehao_org.gif","kiss":"59/kiss2_org.gif","園":"53/yuan_org.gif","團":"11/tuan_org.gif","霧":"68/w_org.gif","颱風":"55/tf_org.gif","沙塵暴":"69/sc_org.gif","晴轉多雲":"d2/qzdy_org.gif","流星":"8e/lx_org.gif","龍捲風":"6a/ljf_org.gif","洪水":"ba/hs2_org.gif","風":"74/gf_org.gif","多雲轉晴":"f3/dyzq_org.gif","彩虹":"03/ch_org.gif","冰雹":"05/bb2_org.gif","微風":"a5/wind_org.gif","陽光":"1a/sunny_org.gif","雪":"00/snow_org.gif","閃電":"e3/sh_org.gif","下雨":"50/rain.gif","陰天":"37/dark_org.gif","粉紅絲帶":"77/pink_org.gif","愛心傳遞":"b8/aixincd_org.gif","歡歡":"c3/liaobuqi_org.gif","樂樂":"66/guanbuzhao_org.gif","管不著愛":"78/2guanbuzhao1_org.gif","愛":"09/ai_org.gif","了不起愛":"11/2liaobuqiai_org.gif","有點困":"68/youdiankun_org.gif","yes":"9e/yes_org.gif","咽回去了":"72/yanhuiqule_org.gif","鴨梨很大":"01/yalihenda_org.gif","羞羞":"42/xiuxiu_org.gif","喜歡你":"6b/xihuang_org.gif","小便屁":"a0/xiaobianpi_org.gif","無奈":"d6/wunai22_org.gif","兔兔":"da/tutu_org.gif","吐舌頭":"98/tushetou_org.gif","頭暈":"48/touyun_org.gif","聽音樂":"d3/tingyinyue_org.gif","睡大覺":"65/shuijiao_org.gif","閃閃紫":"9e/shanshanzi_org.gif","閃閃綠":"a8/shanshanlu_org.gif","閃閃灰":"1e/shanshanhui_org.gif","閃閃紅":"10/shanshanhong_org.gif","閃閃粉":"9d/shanshanfen_org.gif","咆哮":"4b/paoxiao_org.gif","摸頭":"2c/motou_org.gif","真美好":"d2/meihao_org.gif","臉紅自爆":"d8/lianhongzibao_org.gif","哭泣女":"1c/kuqinv_org.gif","哭泣男":"38/kuqinan_org.gif","空":"fd/kong_org.gif","盡情玩":"9f/jinqingwan_org.gif","驚喜":"b8/jingxi_org.gif","驚呆":"58/jingdai_org.gif","胡蘿蔔":"e1/huluobo_org.gif","歡騰去愛":"63/huangtengquai_org.gif","感冒了":"67/ganmao_org.gif","怒了":"ef/fennu_org.gif","我要奮鬥":"a6/fendou123_org.gif","發芽":"95/faya_org.gif","春暖花開":"ca/chunnuanhuakai_org.gif","抽煙":"83/chouyan_org.gif","昂":"31/ang_org.gif","啊":"12/aa_org.gif","自插雙目":"d3/zichashuangmu_org.gif","咦":"9f/yiwen_org.gif","噓噓":"cf/xu_org.gif","我吃":"00/wochiwode_org.gif","喵嗚":"a7/weiqu_org.gif","v5":"c5/v5_org.gif","調戲":"f7/tiaoxi_org.gif","打牙":"d7/taihaoxiaole_org.gif","手賤":"b8/shoujian_org.gif","色":"a1/se_org.gif","噴":"4a/pen_org.gif","你懂的":"2e/nidongde_org.gif","喵":"a0/miaomiao_org.gif","美味":"c1/meiwei_org.gif","驚恐":"46/jingkong_org.gif","感動":"7c/gandong_org.gif","放開":"55/fangkai_org.gif","癡呆":"e8/chidai_org.gif","扯臉":"99/chelian_org.gif","不知所措":"ab/buzhisuocuo_org.gif","白眼":"24/baiyan_org.gif","猥瑣":"e1/weisuo_org.gif","挑眉":"c9/tiaomei_org.gif","挑逗":"3c/tiaodou_org.gif","親耳朵":"1c/qinerduo_org.gif","媚眼":"32/meiyan_org.gif","冒個泡":"32/maogepao_org.gif","囧耳朵":"f0/jiongerduo_org.gif","鬼臉":"14/guilian_org.gif","放電":"fd/fangdian_org.gif","悲劇":"ea/beiju_org.gif","撫摸":"78/touch_org.gif","大汗":"13/sweat_org.gif","大驚":"74/suprise_org.gif","驚哭":"0c/supcry_org.gif","星星眼":"5c/stareyes_org.gif","好困":"8b/sleepy_org.gif","嘔吐":"75/sick_org.gif","加我壹個":"ee/plus1_org.gif","痞痞兔耶":"19/pipioye_org.gif","mua":"c6/muamua_org.gif","面抽":"fd/mianchou_org.gif","大笑":"6a/laugh_org.gif","揉":"d6/knead_org.gif","痞痞兔囧":"38/jiong_org.gif","哈尼兔耶":"53/honeyoye_org.gif","開心":"40/happy_org.gif","咬手帕":"af/handkerchief_org.gif","去":"6b/go_org.gif","暈死了":"a4/dizzy_org.gif","大哭":"af/cry_org.gif","扇子遮面":"a1/coverface_org.gif","怒氣":"ea/angery_org.gif","886":"6f/886_org.gif","白羊":"07/byz2_org.gif","射手":"46/ssz2_org.gif","雙魚":"e2/syz2_org.gif","雙子":"89/szz2_org.gif","天秤":"6b/tpz2_org.gif","水瓶":"1b/spz2_org.gif","處女":"62/cnz2_org.gif","金牛":"3b/jnz2_org.gif","巨蟹":"d2/jxz2_org.gif","獅子":"4a/leo2_org.gif","摩羯":"16/mjz2_org.gif","天蠍座":"09/txz_org.gif","天秤座":"c1/tpz_org.gif","雙子座":"d4/szz_org.gif","雙魚座":"7f/syz_org.gif","射手座":"5d/ssz_org.gif","水瓶座":"00/spz_org.gif","摩羯座":"da/mjz_org.gif","獅子座":"23/leo_org.gif","巨蟹座":"a3/jxz_org.gif","金牛座":"8d/jnz_org.gif","處女座":"09/cnz_org.gif","白羊座":"e0/byz_org.gif","加油":"d4/jiayou_org.gif","國旗":"dc/flag_org.gif","金牌":"f4/jinpai_org.gif","銀牌":"1e/yinpai_org.gif","銅牌":"26/tongpai_org.gif","哨子":"a0/shao.gif","黃牌":"a0/yellowcard.gif","紅牌":"64/redcard.gif","足球":"c0/football.gif","籃球":"2c/bball_org.gif","黑8":"6b/black8_org.gif","排球":"cf/volleyball_org.gif","游泳":"b9/swimming_org.gif","乒乓球":"a5/pingpong_org.gif","投籃":"7a/basketball_org.gif","羽毛球":"77/badminton_org.gif","射門":"e0/zuqiu_org.gif","射箭":"40/shejian_org.gif","舉重":"14/juzhong_org.gif","擊劍":"38/jijian_org.gif","微微笑":"9a/xiaoheweixiao_org.gif","特委屈":"02/xiaoheweiqu_org.gif","我吐":"c1/xiaohetua_org.gif","很生氣":"66/xiaoheshengqi_org.gif","流鼻涕":"08/xiaoheliubiti_org.gif","默默哭泣":"a0/xiaohekuqi_org.gif","小盒汗":"e3/xiaohehan_org.gif","發呆中":"44/xiaohefadai_org.gif","不理你":"a8/xiaohebulini_org.gif","強烈鄙視":"d4/xiaohebishi_org.gif","煩躁":"c5/fanzao_org.gif","呲牙":"c1/ciya_org.gif","有錢":"e6/youqian_org.gif","微笑":"05/weixiao_org.gif","帥爆":"c1/shuaibao_org.gif","生氣":"0a/shengqi_org.gif","生病了":"19/shengbing_org.gif","疲勞":"d1/pilao_org.gif","瞄":"14/miao_org.gif","哭":"79/ku_org.gif","好可憐":"76/kelian_org.gif","緊張":"75/jinzhang_org.gif","驚訝":"dc/jingya_org.gif","激動":"bb/jidong_org.gif","見錢":"2b/jianqian_org.gif","汗了":"7d/han_org.gif","奮鬥":"4e/fendou_org.gif","小人得志":"09/xrdz_org.gif","哇哈哈":"cc/whh_org.gif","歎氣":"90/tq_org.gif","凍結":"d3/sjdj_org.gif","切":"1d/q_org.gif","拍照":"ec/pz_org.gif","怕怕":"7c/pp_org.gif","怒吼":"4d/nh_org.gif","膜拜":"9f/mb2_org.gif","路過":"70/lg_org.gif","淚奔":"34/lb_org.gif","臉變色":"cd/lbs_org.gif","親":"05/kiss_org.gif","恐怖":"86/kb_org.gif","交給我吧":"e2/jgwb_org.gif","歡欣鼓舞":"2b/hxgw_org.gif","高興":"c7/gx3_org.gif","尷尬":"43/gg_org.gif","發嗲":"4e/fd_org.gif","犯錯":"19/fc_org.gif","得意":"fb/dy_org.gif","吵鬧":"fa/cn_org.gif","衝鋒":"2f/cf_org.gif","抽耳光":"eb/ceg_org.gif","差得遠呢":"ee/cdyn_org.gif","被砸":"5a/bz2_org.gif","拜託":"6e/bt_org.gif","必勝":"cf/bs3_org.gif","不關我事":"e8/bgws_org.gif","上火":"64/bf_org.gif","不倒翁":"b6/bdw_org.gif","不錯哦":"79/bco_org.gif","yeah":"1a/yeah_org.gif","喜歡":"5f/xh_org.gif","心動":"5f/xd_org.gif","無聊":"53/wl_org.gif","手舞足蹈":"b2/gx_org.gif","搞笑":"09/gx2_org.gif","痛哭":"eb/gd_org.gif","爆發":"38/fn2_org.gif","發奮":"31/d2_org.gif","不屑":"b0/bx_org.gif","眨眨眼":"3b/zy2_org.gif","雜技":"ec/zs_org.gif","多問號":"17/wh2_org.gif","跳繩":"79/ts_org.gif","強吻":"b1/q3_org.gif","不活了":"37/lb2_org.gif","磕頭":"6a/kt_org.gif","嗚嗚":"55/bya_org.gif","不":"a2/bx2_org.gif","狂笑":"d5/zk_org.gif","冤":"5f/wq2_org.gif","蜷":"87/q2_org.gif","美好":"ae/mh_org.gif","樂和":"5f/m2_org.gif","揪耳朵":"15/j3_org.gif","晃":"bf/h2_org.gif","high":"e7/f_org.gif","蹭":"33/c_org.gif","抱枕":"f4/bz3_org.gif","不公平":"85/bgp_org.gif"};

for (var k in TSINA_FACES) {
	TSINA_API_EMOTIONS[k] = TSINA_FACES[k];
}
//TSINA_API_EMOTIONS['淚'] = "d8/sad.gif";
//嘀咕的表情
//http://images.digu.com/web_res_v1/emotion/**.gif
var DIGU_EMOTIONS = {
    "微笑": "01", "我晕": "02", "口水": "03", "开心": "04", "鄙视": "05", 
    "我汗": "06", "好爽": "07", "偷笑": "08", "暴走": "09", "垂泪": "10", 
    "死定": "11", "傲慢": "12", "发怒": "13", "害羞": "14", "吃惊": "15", 
    "瞌睡": "16", "阴险": "17", "伤心": "18", "郁闷": "19", "摇头": "20", 
    "牛逼": "21", "呕吐": "22", "可怜": "23", "耍酷": "24", "雷死": "25", 
    "怒吼": "26", "啥玩意儿？": "27", 
    "28":"28", "29":"29", "30":"30", "31":"31", "32":"32"
};

//人间的表情 [//smile]
var RENJIAN_EMOTIONS = {
   "smile":[
      "微笑",
      "0px 0px"
   ],
   "heart":[
      "色",
      "-30px 0px"
   ],
   "yum":[
      "满足",
      "-60px 0px"
   ],
   "laugh":[
      "憨笑",
      "-90px 0px"
   ],
   "grin":[
      "可爱",
      "-120px 0px"
   ],
   "tongue":[
      "调皮",
      "-150px 0px"
   ],
   "hot":[
      "得意",
      "-180px 0px"
   ],
   "ambivalent":[
      "不高兴",
      "-210px 0px"
   ],
   "blush":[
      "害羞",
      "-240px 0px"
   ],
   "frown":[
      "低落",
      "-270px 0px"
   ],
   "halo":[
      "炯炯有神",
      "0px -30px"
   ],
   "crazy":[
      "猥琐",
      "-30px -30px"
   ],
   "crying":[
      "哭",
      "-60px -30px"
   ],
   "undecided":[
      "傲慢",
      "-90px -30px"
   ],
   "naughty":[
      "魔鬼",
      "-120px -30px"
   ],
   "lips":[
      "闭嘴",
      "-150px -30px"
   ],
   "nerd":[
      "得意",
      "-180px -30px"
   ],
   "kiss":[
      "亲亲",
      "-210px -30px"
   ],
   "pirate":[
      "海盗",
      "-240px -30px"
   ],
   "gasp":[
      "惊讶",
      "-270px -30px"
   ],
   "foot":[
      "擦汗",
      "0px -60px"
   ],
   "largegasp":[
      "衰",
      "-30px -60px"
   ],
   "veryangry":[
      "抓狂",
      "-60px -60px"
   ],
   "angry":[
      "无奈",
      "-90px -60px"
   ],
   "confused":[
      "晕",
      "-120px -60px"
   ],
   "sick":[
      "我吐",
      "-150px -60px"
   ],
   "moneymouth":[
      "吐钱",
      "-180px -60px"
   ],
   "ohnoes":[
      "糗大了",
      "-210px -60px"
   ],
   "wink":[
      "眨眼",
      "-240px -60px"
   ],
   "sarcastic":[
      "阴险",
      "-270px -60px"
   ],
   "up":[
      "顶",
      "0px -90px"
   ],
   "down":[
      "鄙视",
      "-30px -90px"
   ],
   "candle":[
      "蜡烛",
      "-60px -90px"
   ],
   "flower":[
      "鲜花",
      "-90px -90px"
   ],
   "ribbon":[
      "丝带",
      "-120px -90px"
   ]
};

// TSOHU 表情
// .find('i').each(function(){console.log('"' + $(this).attr('title') + '": "' + $(this).attr('class') + '",')});
var TSOHU_EMOTIONS_URL_PRE = 'http://s3.cr.itc.cn/img/';
var TSOHU_FACE_TPL = '[{{name}}]';
var TSOHU_EMOTIONS = {
"地球一小时": "i2/t/178.gif",
"盐": "t/536.gif",
"心相映": "t/532.gif",
"急救箱": "t/531.gif",
"地震": "t/530.gif",
"蜡烛": "t/425.gif",
//"握手": "x x53",
"蛋糕": "t/527.gif",
"内裤": "t/528.gif",
"内衣": "t/529.gif",
"雪": "t/526.gif",
"福": "t/519.gif",
"微笑": "i3/t/2026.gif",
"色": "i3/t/2027.gif",
"呲牙": "i3/t/2028.gif",
"偷笑": "i3/t/2029.gif",
"害羞": "i3/t/2030.gif",
"大哭": "i3/t/2031.gif",
"哭": "i3/t/061.gif",
"酷": "i3/t/2033.gif",
"发火": "i3/t/2034.gif",
"怒": "i3/t/2035.gif",
"疑问": "i3/t/2036.gif",
"感叹": "i3/t/2037.gif",
"调皮": "i3/t/2038.gif",
"眨眼": "i3/t/2039.gif",
"寒": "i3/t/2040.gif",
"睡觉": "i3/t/2041.gif",
"困": "i3/t/2042.gif",
"不满": "i3/t/2043.gif",
"噘嘴": "i3/t/2044.gif",
"听歌": "i3/t/2045.gif",
"汗": "i3/t/2046.gif",
"脸红": "i3/t/2047.gif",
"耳语": "i3/t/2048.gif",
"嘘": "i3/t/2049.gif",
"吐": "i3/t/2050.gif",
"馋": "i3/t/2051.gif",
"鄙视": "i3/t/2052.gif",
"讽刺": "i3/t/2053.gif",
"发呆": "i3/t/2054.gif",
"晕": "i3/t/2055.gif",
"被踹": "i3/t/2056.gif",
"衰": "i3/t/2057.gif",
"受伤": "i3/t/2058.gif",
"海盗": "i3/t/2059.gif",
"闭嘴": "i3/t/2060.gif",
"佐罗": "i3/t/2061.gif"
};

// TQQ表情
// http://mat1.gtimg.com/www/mb/images/face/14.gif
// .find('a').each(function(i, item){console.log('"' + $(this).attr('title') + '"' + ': ' + '"' + $(this).attr('class').substring(1) + '.gif",');});
//var d = a.find('img').each(function(){
//    console.log('"' +$(this).attr('k')+ $(this).attr('title') + '"' + ': ' + '"' + $(this).attr('src') + '",');
//    }
//);
var TQQ_EMOTIONS_URL_PRE = 'http://mat1.gtimg.com/www/mb/images/';
var TQQ_FACE_TPL = '/{{name}}';
var TQQ_EMOTIONS = {
	"微笑": "face/14.gif",
	"撇嘴": "face/1.gif",
	"色": "face/2.gif",
	"发呆": "face/3.gif",
	"得意": "face/4.gif",
	"流泪": "face/5.gif",
	"害羞": "face/6.gif",
	"闭嘴": "face/7.gif",
	"睡": "face/8.gif",
	"大哭": "face/9.gif",
	"尴尬": "face/10.gif",
	"发怒": "face/11.gif",
	"调皮": "face/12.gif",
	"呲牙": "face/13.gif",
	"惊讶": "face/0.gif",
	"难过": "face/15.gif",
	"酷": "face/16.gif",
	"冷汗": "face/96.gif",
	"抓狂": "face/18.gif",
	"吐": "face/19.gif",
	"偷笑": "face/20.gif",
	"可爱": "face/21.gif",
	"白眼": "face/22.gif",
	"傲慢": "face/23.gif",
	"饥饿": "face/24.gif",
	"困": "face/25.gif",
	"惊恐": "face/26.gif",
	"流汗": "face/27.gif",
	"憨笑": "face/28.gif",
	"大兵": "face/29.gif",
	"奋斗": "face/30.gif",
	"咒骂": "face/31.gif",
	"疑问": "face/32.gif",
	"嘘": "face/33.gif",
	"晕": "face/34.gif",
	"折磨": "face/35.gif",
	"衰": "face/36.gif",
	"骷髅": "face/37.gif",
	"敲打": "face/38.gif",
	"再见": "face/39.gif",
	"擦汗": "face/97.gif",
	"抠鼻": "face/98.gif",
	"鼓掌": "face/99.gif",
	"糗大了": "face/100.gif",
	"坏笑": "face/101.gif",
	"左哼哼": "face/102.gif",
	"右哼哼": "face/103.gif",
	"哈欠": "face/104.gif",
	"鄙视": "face/105.gif",
	"委屈": "face/106.gif",
	"快哭了": "face/107.gif",
	"阴险": "face/108.gif",
	"亲亲": "face/109.gif",
	"吓": "face/110.gif",
	"可怜": "face/111.gif",
	"菜刀": "face/112.gif",
	"西瓜": "face/89.gif",
	"啤酒": "face/113.gif",
	"篮球": "face/114.gif",
	"乒乓": "face/115.gif",
	"咖啡": "face/60.gif",
	"饭": "face/61.gif",
	"猪头": "face/46.gif",
	"玫瑰": "face/63.gif",
	"凋谢": "face/64.gif",
	"示爱": "face/116.gif",
	"爱心": "face/66.gif",
	"心碎": "face/67.gif",
	"蛋糕": "face/53.gif",
	"闪电": "face/54.gif",
	"炸弹": "face/55.gif",
	"刀": "face/56.gif",
	"足球": "face/57.gif",
	"瓢虫": "face/117.gif",
	"便便": "face/59.gif",
	"月亮": "face/75.gif",
	"太阳": "face/74.gif",
	"礼物": "face/69.gif",
	"拥抱": "face/49.gif",
	"强": "face/76.gif",
	"弱": "face/77.gif",
	"握手": "face/78.gif",
	"胜利": "face/79.gif",
	"抱拳": "face/118.gif",
	"勾引": "face/119.gif",
	"拳头": "face/120.gif",
	"差劲": "face/121.gif",
	"爱你": "face/122.gif",
	"NO": "face/123.gif",
	"OK": "face/124.gif",
	"爱情": "face/42.gif",
	"飞吻": "face/85.gif",
	"跳跳": "face/43.gif",
	"发抖": "face/41.gif",
	"怄火": "face/86.gif",
	"转圈": "face/125.gif",
	"磕头": "face/126.gif",
	"回头": "face/127.gif",
	"跳绳": "face/128.gif",
	"挥手": "face/129.gif",
	"激动": "face/130.gif",
	"街舞": "face/131.gif",
	"献吻": "face/132.gif",
	"左太极": "face/133.gif",
	"右太极": "face/134.gif",
	
	"b囧": "cFace/b1.gif",
	"b惊": "cFace/b2.gif",
	"b大笑": "cFace/b3.gif",
	"b闪电": "cFace/b4.gif",
	"b再见": "cFace/b5.gif",
	"b乌鸦": "cFace/b6.gif",
	"b口水": "cFace/b7.gif",
	"b飞": "cFace/b8.gif",
	"b得意": "cFace/b9.gif",
	"b吃": "cFace/b10.gif",
	"b走着": "cFace/b11.gif",
	"b路过": "cFace/b12.gif",
	"b流汗": "cFace/b13.gif",
	
	"c爱心": "cFace/c1.gif",
	"c擦汗": "cFace/c2.gif",
	"c呲牙": "cFace/c3.gif",
	"c大哭": "cFace/c4.gif",
	"c大笑": "cFace/c5.gif",
	"c发呆": "cFace/c6.gif",
	"c激动": "cFace/c7.gif",
	"c可爱": "cFace/c8.gif",
	"c厉害": "cFace/c9.gif",
	"c敲打": "cFace/c10.gif",
	"c色": "cFace/c11.gif",
	"c生气": "cFace/c12.gif",
	"c调皮": "cFace/c13.gif",
	"c偷笑": "cFace/c14.gif",
	"c吐": "cFace/c15.gif",
	"c摇头": "cFace/c16.gif",
	"c再见": "cFace/c17.gif",
	"c折磨": "cFace/c18.gif",
	
	"j吃饭": "cFace/j1.gif",
	"j飞吻": "cFace/j2.gif",
	"j浮云": "cFace/j3.gif",
	"j鼓掌": "cFace/j4.gif",
	"j害羞": "cFace/j5.gif",
	"j囧": "cFace/j6.gif",
	"j纠结": "cFace/j7.gif",
	"j开心": "cFace/j8.gif",
	"j哭泣": "cFace/j9.gif",
	"j晚安": "cFace/j10.gif",
	"j汗": "cFace/j11.gif",
	"j无奈": "cFace/j12.gif",
	"j招手": "cFace/j13.gif",
	"j震惊": "cFace/j14.gif",
	"j咒骂": "cFace/j15.gif"

};

// t163
var T163_EMOTIONS_URL_PRE = 'http://img1.cache.netease.com/t/face/';
var T163_FACE_TPL = '[{{name}}]';
var T163_EMOTIONS = {
"勾引": "yunying/gouyin.gif",
"纠结": "yunying/jiujie.gif",
"开心": "yunying/kaixin.gif",
"困死了": "yunying/kunsile.gif",
"路过": "yunying/luguo.gif",
"冒泡": "yunying/maopao.gif",
"飘走": "yunying/piaozou.gif",
"思考": "yunying/sikao.gif",
"我顶": "yunying/woding.gif",
"我晕": "yunying/woyun.gif",
"抓狂": "yunying/zhuakuang.gif",
"装酷": "yunying/zhuangku.gif",
"福": "default/fu.gif",
"红包": "default/hongbao.gif",
"菊花": "default/jvhua.gif",
"蜡烛": "default/lazhu.gif",
"礼物": "default/liwu.gif",
"圣诞老人": "default/sdlr.gif",
"圣诞帽": "default/sdm.gif",
"圣诞树": "default/sds.gif",
"崩溃": "default/bengkui.gif",
"鄙视你": "default/bishini.gif",
"不说": "default/bushuo.gif",
"大哭": "default/daku.gif",
"飞吻": "default/feiwen.gif",
"工作忙": "default/gongzuomang.gif",
"鼓掌": "default/guzhang.gif",
"害羞": "default/haixiu.gif",
"坏": "default/huai.gif",
"坏笑": "default/huaixiao.gif",
"教训": "default/jiaoxun.gif",
"惊讶": "default/jingya.gif",
"可爱": "default/keai.gif",
"老大": "default/laoda.gif",
"欠揍": "default/qianzou.gif",
"撒娇": "default/sajiao.gif",
"色迷迷": "default/semimi.gif",
"送花": "default/songhua.gif",
"偷笑": "default/touxiao.gif",
"挖鼻孔": "default/wabikou.gif",
"我吐": "default/wotu.gif",
"嘘": "default/xu.gif",
"仰慕你": "default/yangmuni.gif",
"yeah": "default/yeah.gif",
"疑问": "default/yiwen.gif",
"晕": "default/yun.gif",
"砸死你": "default/zasini.gif",
"眨眼": "default/zhayan.gif",
"扭扭": "ali/niuniu.gif",
"转圈圈": "ali/feng.gif",
"踢踏舞": "ali/tita.gif",
"强": "ali/qiang.gif",
"跳舞": "ali/niu.gif",
"蜷": "ali/juan.gif",
"吃惊": "ali/bie.gif",
"我汗": "ali/liuhan.gif",
"呐喊": "ali/aaa.gif",
"生病": "ali/dahan.gif",
"隐身": "ali/yinshen.gif",
"放松": "ali/jian.gif",
"捶地": "ali/bugongping.gif",
"嗯": "ali/diantou.gif",
"撒花": "ali/saqian.gif",
"撒花": "ali/saqian.gif",
"心": "ali/xin.gif",
"囧": "ali/jiong.gif",
"害怕": "ali/leng.gif",
"冷": "ali/han.gif",
"震惊": "ali/jingya.gif",
"怒": "ali/nuqi.gif",
"狂笑": "ali/kuangxiao.gif",
"渴望": "ali/kewang.gif",
"飘过": "ali/piaoguo.gif",
"转圈哭": "ali/zhuanquanku.gif",
"得瑟": "ali/lala.gif",
"hi": "ali/hi.gif",
"闪电": "ali/jing.gif",
"同意": "ali/erduo.gif",
"星星眼": "ali/a.gif",
"爆头": "popb/baotou.gif",
"唱歌": "popb/changge.gif",
"嘲笑": "popb/chaoxiao.gif",
"抽烟": "popb/chouyan.gif",
"大笑": "popb/daxiao.gif",
"淡定": "popb/danding.gif",
"疯了": "popb/fengle.gif",
"感动": "popb/gandong.gif",
"哈哈": "popb/haha.gif",
"汗": "popb/han.gif",
"好冷": "popb/haoleng.gif",
"哼哒": "popb/hengda.gif",
"警告": "popb/jinggao.gif",
"跳跳": "popb/kaiqiang.gif",
"困": "popb/kun.gif",
"泪奔": "popb/leiben.gif",
"卖萌": "popb/maimeng.gif",
"拍手": "popb/paishou.gif",
"路过这里": "popb/piaoguo.gif",
"杀无赦": "popb/shawushe.gif",
"烧香": "popb/shaoxiang.gif",
"掏鼻孔": "popb/taobikong.gif",
"舔舔": "popb/tiantian.gif",
"开枪": "popb/tiaotiao.gif",
"吐口水": "popb/tukoushui.gif",
"瞎得瑟": "popb/xiadese.gif",
"吆西": "popb/yaoxi.gif",
"晕倒": "popb/yundao.gif",
"早安": "popb/zaoan.gif",
"揍你": "popb/zouni.gif",
};

//http://www.douban.com/photos/album/46634840/
var YANWENZI = {
    "ʅ(‾◡◝)ʃ": "ʅ(‾◡◝)ʃ",
    "♪(´ε｀)": "♪(´ε｀)",
    "<(￣︶￣)>": "得意 <(￣︶￣)>",
    "╮(╯_╰)╭": "沒辦法啦 ╮(╯_╰)╭",
    "(⊙ˍ⊙)": "(⊙ˍ⊙)",
    "(￣ˇ￣)": "(￣ˇ￣)",
    "（¯﹃¯）": "（¯﹃¯）",
    "”(*´ｪ`*)”": "”(*´ｪ`*)”",
    "<(▰˘◡˘▰)>": "<(▰˘◡˘▰)>",
    "(●'◡'●)ﾉ♥": "(●'◡'●)ﾉ♥",
    "(・ω< )★": "(・ω< )★",
    "(☍﹏⁰)": "(☍﹏⁰) 流泪。。",
    "(♥◠‿◠)ﾉ": "(♥◠‿◠)ﾉ",
    "(*ﾟｪﾟ*)": "(*ﾟｪﾟ*)",
    "(〒ˍ〒)": "(〒ˍ〒)",
    "╯-__-)╯ ╩╩": "╯-__-)╯ ╩╩",
    "(≧▽≦)": "(≧▽≦)",
    "(✿✪‿✪｡)ﾉ": "(✿✪‿✪｡)ﾉ",
    "囧rz": "囧rz",
    "orz": "orz",
    "✧ (≖ ‿ ≖)✧": "✧ (≖ ‿ ≖)✧",
    
    "╮(╯▽╰)╭": "沒辦法啦 ╮(╯▽╰)╭",
    "┑(￣。￣)┍": "沒辦法啦 ┑(￣。￣)┍",
    "ƪ(΄◞ิ۝◟ิ‵)ʃ": "ƪ(΄◞ิ۝◟ิ‵)ʃ",
    "└(^o^)┘": "└(^o^)┘; 偶頭好狀壯ㄋㄟ```",
    "(ˇˍˇ)": "我想想 (ˇˍˇ)",
    
    "o(╯□╰)o": "o(╯□╰)o",
    "（￣ c￣）": "（￣ c￣）",
    "Σ( ° △ °|||)︴": "Σ( ° △ °|||)︴",
    "<(=﹫_﹫;=)?>": "<(=﹫_﹫;=)?>",
    "(@^_^@)": "(@^_^@)",
    "(๑>◡<๑)": "(๑>◡<๑)",
    "ヽ(*΄◞ิ౪◟ิ‵ *)": "ヽ(*΄◞ิ౪◟ิ‵ *)",
    
    "ઈ(◕ั◡◕ั)☄*ﾟ*": "ઈ(◕ั◡◕ั)☄*ﾟ*",
    "(´･ω･｀) ": "(´･ω･｀) ",
    
    "( -'`-; )": "( -'`-; )",
    "Σ(｀д′*ノ)ノ": "Σ(｀д′*ノ)ノ",
    "＜(╰﹏╯)╯": "＜(╰﹏╯)╯",
    "罒ω罒": "罒ω罒",
    "(°Д°≡°д°)ｴｯ!?": "(°Д°≡°д°)ｴｯ!?",
    "ಥ_______ಥ": "ಥ_______ಥ",
    "(‵﹏′)": "(‵﹏′)",
    "╰ ε ╯": "╰ ε ╯",
    "(〃ω〃)彡": "(〃ω〃)彡",
    "(－－〆)": "(－－〆)",
    "(///▽///)": "(///▽///)",
    "(///ω///)": "(///ω///)",
    "≧︿≦": "≧︿≦",
    "(〃㉦〃)": "(〃㉦〃)",
    "˙ω˙": "˙ω˙",
    "⁽⁽(ཀ д ཀ)⁾⁾": "⁽⁽(ཀ д ཀ)⁾⁾",
    "乛 з乛": "乛 з乛",
    "(乛乛)": "(乛乛)",
    "(*°▽°*)": "(*°▽°*)",
    "<(ll°д°ll)>!": "<(ll°д°ll)>!",
    
    "o(∩∩)o": "o(∩∩)o",
    "✪ω✪": "✪ω✪",
    "\^O^/": "\^O^/",
    "＼(*´▽`)／": "＼(*´▽`)／",
    "(*´v`)": "(*´v`)",
    "(˘❥˘)": "(˘❥˘)",
    "(♩￢3￢)": "(♩￢3￢)",
    "( ^３^ )╱~~": "( ^３^ )╱~~",
    "ლ(╹◡╹ლ )": "ლ(╹◡╹ლ )",
    "ლ◕ิ‿◕ิლ": "ლ◕ิ‿◕ิლ",
    "ლↀѡↀლ": "ლↀѡↀლ",
    "／人◕ ‿‿ ◕人＼": "／人◕ ‿‿ ◕人＼",
    "(´・ω・｀)": "(´・ω・｀)",
    "(┬＿┬)": "(┬＿┬)",
    "(T_T)": "(T_T)",
    "(^_^)": "(^_^)",
    "(OvO)": "(OvO)",
    "(〃^∇^)o": "(〃^∇^)o",
    "(﹁\"﹁)": "(﹁\"﹁)",
    "(￣◇￣;)": "(￣◇￣;)",
    "o(￣▽￣)o": "o(￣▽￣)o",
    "o(*≧▽≦)ツ": "o(*≧▽≦)ツ",
    ">д<": ">д<",
    "ಠ_ಠ": "ಠ_ಠ",
    "Ͼ_Ͽ": "Ͼ_Ͽ",
    " ⃔⌄ ⃔": " ⃔⌄ ⃔",
    "→_→": "→_→",
    "(๑°3°๑)": "(๑°3°๑)",
    "(♩￢3￢)": "(♩￢3￢)",
    "｡◕‿◕｡": "｡◕‿◕｡",
    "(￣ε(#￣)": "被打一巴掌 (￣ε(#￣)",
    "(︶︿︶)╭∩╮": "哼.哼.哼 (︶︿︶)╭∩╮",
    "(╬▔＾▔)凸": "(╬▔＾▔)凸",
    "(^_-)-☆": "(^_-)-☆",
    "(*^︹^*)": "(*^︹^*)",
    "(*^﹏^*)": "(*^﹏^*)",
    "&( ^___^ )&": "&( ^___^ )& 麻花辫女孩",
    "(,,Ծ‸Ծ,,)": "(,,Ծ‸Ծ,,)",
    "v( ^-^(ё_ёゝ": "v( ^-^(ё_ёゝ 我女喷油",
    "٩͡[๏̯͡๏]۶": "٩͡[๏̯͡๏]۶",
    "ℰ⋆‿⋆ℰ": "ℰ⋆‿⋆ℰ 卷发的小姑凉",
    "இwஇ": "இwஇ",
    "థ౪థ": "థ౪థ",
    "(*☉౪⊙*)": "(*☉౪⊙*) 监狱兔",
    "ヾ(o゜_,゜o)ノ": "ヾ(o゜_,゜o)ノ 有酒窝的孩纸",
    "(,,゜c_,゜*)ノ": "(,,゜c_,゜*)ノ 挂鼻环的青年你伤不起~",
    "=@~@=": "=@~@= 一个看到美眉就紧张+脸红的大学生",
    "<。)#)))≦": "<。)#)))≦ 烤魚",
    "^m^": "^m^",
    "(｡・`ω´･)": "(｡・`ω´･)",
    "(゜_゜>)": "(゜_゜>)你说神马？",
    "(;_;)/~~~": "(;_;)/~~~",
    "(‘;’)": "(‘;’) 我不系斗鸡眼",
    "(^人^)": "(^人^)",
    "m(_ _)m": "m(_ _)m",
    "( ′θ`)": "( ′θ`)",
    " (ノへ￣、)": " (ノへ￣、)",
    "ˇ▽ˇ": "ˇ▽ˇ",
    "(.Q.)": "(.Q.)",
    "╰（‵□′）╯": "╰（‵□′）╯",
    "♥(꒪.̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̨̨̨̨̨̨̨̨̨̨̨̨.̸̸̨̨꒪ )": "流鼻血 ♥(꒪.̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̨̨̨̨̨̨̨̨̨̨̨̨.̸̸̨̨꒪ )",
    "~Ⴚ(●ტ●)Ⴢ~": "~Ⴚ(●ტ●)Ⴢ~",
    "٩(×̯×)۶": "٩(×̯×)۶",
    "٩(•̮̮̃•̃)۶": "٩(•̮̮̃•̃)۶",
    "٩(-̮̮̃-̃)۶": "٩(-̮̮̃-̃)۶",
    "(๑꒪◞౪◟꒪๑)": "(๑꒪◞౪◟꒪๑)",
    "✷(ꇐ‿ꇐ)✷": "✷(ꇐ‿ꇐ)✷",
    "<( ‵□′)───C＜─___-)||": "捏脸 <( ‵□′)───C＜─___-)||",
    "_(:3」∠)_": "_(:3」∠)_",
    "__ノ乙(、'ノ、)_": "__ノ乙(、'ノ、)_",
};

var TAOBAO_FACES_URL_PRE = 'http://t.taobao.org/theme/taobao/emotions/';
var TAOBAO_FACES_TPL = '[^{{name}}^]';
var TAOBAO_FACES = {
    '微笑': '0.gif',
    '害羞': '1.gif',
    '吐舌头': '2.gif',
    '偷笑': '3.gif',
    '爱慕': '4.gif',
    '大笑': '5.gif',
    '跳舞': '6.gif',
    '飞吻': '7.gif',
    '安慰': '8.gif',
    '抱抱': '9.gif',
    '加油': '10.gif',
    '胜利': '11.gif',
    '强': '12.gif',
    '亲亲': '13.gif',
    '花痴': '14.gif',
    '露齿笑': '15.gif',
    '查找': '16.gif',
    '呼叫': '17.gif',
    '算账': '18.gif',
    '财迷': '19.gif',
    '好主意': '20.gif',
    '鬼脸': '21.gif',
    '天使': '22.gif',
    '拜拜': '23.gif',
    '流口水': '24.gif',
    '享受': '25.gif',
    '色情狂': '26.gif',
    '呆若木鸡': '27.gif',
    '思考': '28.gif',
    '迷惑': '29.gif',
    '疑问': '30.gif',
    '没钱了': '31.gif',
    '无聊': '32.gif',
    '怀疑': '33.gif',
    '嘘': '34.gif',
    '小样': '35.gif',
    '摇头': '36.gif',
    '感冒': '37.gif',
    '尴尬': '38.gif',
    '傻笑': '39.gif',
    '不会吧\t': '40.gif',
    '无奈': '41.gif',
    '流汗': '42.gif',
    '凄凉': '43.gif',
    '困了': '44.gif',
    '晕': '45.gif',
    '忧伤': '46.gif',
    '委屈': '47.gif',
    '悲泣': '48.gif',
    '大哭': '49.gif',
    '痛哭': '50.gif',
    'I服了U': '51.gif',
    '对不起': '52.gif',
    '再见': '53.gif',
    '皱眉': '54.gif',
    '好累': '55.gif',
    '生病': '56.gif',
    '吐': '57.gif',
    '背': '58.gif',
    '惊讶': '59.gif',
    '惊愕': '60.gif',
    '闭嘴': '61.gif',
    '欠扁': '62.gif',
    '鄙视你': '63.gif',
    '大怒': '64.gif',
    '生气': '65.gif',
    '财神': '66.gif',
    '学习雷锋': '67.gif',
    '恭喜发财': '68.gif',
    '小二': '69.gif',
    '老大': '70.gif',
    '邪恶': '71.gif',
    '单挑': '72.gif',
    'CS': '73.gif',
    '隐形人': '74.gif',
    '炸弹': '75.gif',
    '惊声尖叫': '76.gif',
    '漂亮MM': '77.gif',
    '帅哥': '78.gif',
    '招财猫': '79.gif',
    '成交': '80.gif',
    '鼓掌': '81.gif',
    '握手': '82.gif',
    '红唇': '83.gif',
    '玫瑰': '84.gif',
    '残花': '85.gif',
    '爱心': '86.gif',
    '心碎': '87.gif',
    '钱': '88.gif',
    '购物': '89.gif',
    '礼物': '90.gif',
    '收邮件': '91.gif',
    '电话': '92.gif',
    '举杯庆祝': '93.gif',
    '时钟': '94.gif',
    '等待': '95.gif',
    '很晚了': '96.gif',
    '飞机': '97.gif',
    '支付宝': '98.gif'
};

var FACE_TYPES = [
    ['tsina', TSINA_FACES, TSINA_FACE_URL_PRE, TSINA_FACE_TPL, '新浪'],      
    ['tqq', TQQ_EMOTIONS, TQQ_EMOTIONS_URL_PRE, TQQ_FACE_TPL, '腾讯'],
    ['yanwenzi', YANWENZI, null, null, '颜文字'],
    ['t_taobao', TAOBAO_FACES, TAOBAO_FACES_URL_PRE, TAOBAO_FACES_TPL, '淘宝'],
    ['tsohu', TSOHU_EMOTIONS, TSOHU_EMOTIONS_URL_PRE, TSOHU_FACE_TPL, '搜狐'],
    ['t163', T163_EMOTIONS, T163_EMOTIONS_URL_PRE, T163_FACE_TPL, '网易'],
];
